import { audioContext } from 'waves-audio';
import client from '../core/client';
import MobileDetect from 'mobile-detect';
import SegmentedView from '../views/SegmentedView';
import Service from '../core/Service';
import serviceManager from '../core/serviceManager';

// @todo - define if we keep this
import * as adapter from 'webrtc-adapter';
adapter.disableLog(true);

// to be added
// + “video-input”: needs video input
// + “video-audio-input”: needs video input
// + DeviceMotion/Orientation conditions generated by the motion-input module

const defaultDefinitions = [
  {
    id: 'web-audio',
    check: function() {
      return !!audioContext;
    },
    interactionHook: function() {
      if (!client.platform.isMobile)
        return;

      const g = audioContext.createGain();
      g.connect(audioContext.destination);
      g.gain.value = 0.000000001; // -180dB ?

      const o = audioContext.createOscillator();
      o.connect(g);
      o.frequency.value = 20;
      o.start(0);

      // prevent android to stop audio by keping the oscillator active
      if (client.platform.os !== 'android')
        o.stop(audioContext.currentTime + 0.01);
    }
  },
  {
    // @note: `touch` feature workaround
    // cf. http://www.stucox.com/blog/you-cant-detect-a-touchscreen/
    id: 'mobile-device',
    check: function() {
      return client.platform.isMobile;
    }
  },
  {
    id: 'audio-input',
    check: function() {
      return !!navigator.getUserMedia;
    },
    startHook: function() {
      navigator.getUserMedia({ audio: true }, function(stream) {
        stream.getAudioTracks()[0].stop();
      }, function (err) {
        throw err;
      });
    }
  }
];


const SERVICE_ID = 'service:platform';

class Platform extends Service {
  constructor() {
    super(SERVICE_ID, false);

    const defaults = {
      viewCtor: SegmentedView,
      viewPriority: 20,
    };

    this.configure(defaults);

    this._requiredFeatures = new Set();
    this._featureDefinitions = {};

    defaultDefinitions.forEach((def) => this.addFeatureDefinition(def));
  }

  /** @inheritdoc */
  configure(options) {
    if (options.features) {
      let features = options.features;

      if (typeof features === 'string')
        features = [features];

      this.requireFeature(...features);
      delete options.features;
    }

    super.configure(options);
  }

  /** @inheritdoc */
  init() {
    this._defineAudioFileExtention();
    this._definePlatform();
    // resolve required features from the application
    client.compatible = this.resolveRequiredFeatures();

    this.viewCtor = this.options.viewCtor;
    this.view = this.createView();
  }

  /** @inheritdoc */
  start() {
    super.start();

    if (!this.hasStarted)
      this.init();

    if (client.compatible)
      this.ready();
    else
      this.show();
  }

  /**
   * Add a new feature definition or override an existing one.
   * @param {Object} obj - The definition of the feature.
   * @param {String} obj.id - The id of the definition.
   * @param {Function} obj.check - A function returning true if the feature is
   *  available or false otherwise.
   * @param {Function} [obj.startHook=undefined] - A function to be executed by the
   *  `welcome` service when starting.
   * @param {Function} [obj.interactionHook=undefined] - A function to be executed by the
   *  `welcome` service when the user interact with the device (i.e. on `click` or
   *  `touchstart`).
   */
  addFeatureDefinition(obj) {
    this._featureDefinitions[obj.id] = obj;
  }

  /**
   * Add feature(s) to the ones required by the application.
   * @param {...String} features - The id(s) of the feature(s) to be required.
   */
  requireFeature(...features) {
    features.forEach((id) => this._requiredFeatures.add(id));
  }

  /**
   * Execute all `check` functions according to the required features
   * @return {Boolean} - true if all checks pass, false otherwise.
   */
  resolveRequiredFeatures() {
    let result = true;

    this._requiredFeatures.forEach((feature) => {
      const checkFunction = this._featureDefinitions[feature].check;

      if (!(typeof checkFunction === 'function'))
        throw new Error(`No check function defined for ${feature} feature`);

      result = result && checkFunction();
    });

    return result;
  }

  /**
   * Returns the list of the functions to be executed on welcome `start` lifecycle.
   * @return {Array}
   */
  getStartHooks() {
    return this._getHooks('startHook');
  }

  /**
   * Returns the list of the functions to be executed on welcome when the user
   * interacts with the application.
   * @return {Array}
   */
  getInteractionHooks() {
    return this._getHooks('interactionHook');
  }

  /** @private */
  _getHooks(type) {
    const hooks = [];

    this._requiredFeatures.forEach((feature) => {
      const hook = this._featureDefinitions[feature][type];

      if (hook)
        hooks.push(hook);
    });

    return hooks;
  }

  /**
   * Populate `client.platform` with the prefered audio file extention
   * for the platform.
   */
  _defineAudioFileExtention() {
    const a = document.createElement('audio');
    // http://diveintohtml5.info/everything.html
    if (!!(a.canPlayType && a.canPlayType('audio/mpeg;'))) {
      client.platform.audioFileExt = '.mp3';
    } else if (!!(a.canPlayType && a.canPlayType('audio/ogg; codecs="vorbis"'))) {
      client.platform.audioFileExt = '.ogg';
    } else {
      client.platform.audioFileExt = '.wav';
    }
  }

  /**
   * Populate `client.platform` with the os name.
   */
  _definePlatform() {
    const ua = window.navigator.userAgent
    const md = new MobileDetect(ua);

    client.platform.isMobile = (md.mobile() !== null); // true if phone or tablet
    client.platform.os = (function() {
      const os = md.os();

      if (os === 'AndroidOS')
        return 'android';
      else if (os === 'iOS')
        return 'ios';
      else
        return 'other';
    })();
  }
}

serviceManager.register(SERVICE_ID, Platform);

export default Platform;
