'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _defineProperty2 = require('babel-runtime/helpers/defineProperty');

var _defineProperty3 = _interopRequireDefault(_defineProperty2);

var _toConsumableArray2 = require('babel-runtime/helpers/toConsumableArray');

var _toConsumableArray3 = _interopRequireDefault(_toConsumableArray2);

var _set = require('babel-runtime/core-js/set');

var _set2 = _interopRequireDefault(_set);

var _getPrototypeOf = require('babel-runtime/core-js/object/get-prototype-of');

var _getPrototypeOf2 = _interopRequireDefault(_getPrototypeOf);

var _classCallCheck2 = require('babel-runtime/helpers/classCallCheck');

var _classCallCheck3 = _interopRequireDefault(_classCallCheck2);

var _createClass2 = require('babel-runtime/helpers/createClass');

var _createClass3 = _interopRequireDefault(_createClass2);

var _possibleConstructorReturn2 = require('babel-runtime/helpers/possibleConstructorReturn');

var _possibleConstructorReturn3 = _interopRequireDefault(_possibleConstructorReturn2);

var _get2 = require('babel-runtime/helpers/get');

var _get3 = _interopRequireDefault(_get2);

var _inherits2 = require('babel-runtime/helpers/inherits');

var _inherits3 = _interopRequireDefault(_inherits2);

var _wavesAudio = require('waves-audio');

var _client = require('../core/client');

var _client2 = _interopRequireDefault(_client);

var _mobileDetect = require('mobile-detect');

var _mobileDetect2 = _interopRequireDefault(_mobileDetect);

var _screenfull = require('screenfull');

var _screenfull2 = _interopRequireDefault(_screenfull);

var _SegmentedView = require('../views/SegmentedView');

var _SegmentedView2 = _interopRequireDefault(_SegmentedView);

var _Service2 = require('../core/Service');

var _Service3 = _interopRequireDefault(_Service2);

var _serviceManager = require('../core/serviceManager');

var _serviceManager2 = _interopRequireDefault(_serviceManager);

var _webrtcAdapter = require('webrtc-adapter');

var adapter = _interopRequireWildcard(_webrtcAdapter);

function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } else { var newObj = {}; if (obj != null) { for (var key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) newObj[key] = obj[key]; } } newObj.default = obj; return newObj; } }

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

adapter.disableLog(true);

// @todo - to be added
// + “video-input”: needs video input
// + “video-audio-input”: needs video input
// + DeviceMotion/Orientation conditions generated by the motion-input module

/**
 * Structure of the definition of a feature to be tested.
 * @typedef {Object} module:soundworks/client.Platform~definition
 * @property {String} id - Id of the definition.
 * @property {Function} check - A function that should return `true` if the
 *  feature is available on the platform, `false` otherwise.
 * @property {Function} [interactionHook] - A function to be executed on the
 *  first interaction (i.e. `click` or `touchstart`) of the user with application
 *  (for example, to initialize AudioContext on iOS devices).
 * @property {Function} [interactionHook] - A function to be executed on start
 *  (for example to ask access to microphone or geolocation).
 */

// @todo - define if we keep this in defaults
var defaultDefinitions = [{
  id: 'web-audio',
  check: function check() {
    return !!_wavesAudio.audioContext;
  },
  interactionHook: function interactionHook() {
    if (!_client2.default.platform.isMobile) return;

    var g = _wavesAudio.audioContext.createGain();
    g.connect(_wavesAudio.audioContext.destination);
    g.gain.value = 0.000000001; // -180dB ?

    var o = _wavesAudio.audioContext.createOscillator();
    o.connect(g);
    o.frequency.value = 20;
    o.start(0);

    // prevent android to stop audio by keping the oscillator active
    if (_client2.default.platform.os !== 'android') o.stop(_wavesAudio.audioContext.currentTime + 0.01);
  }
}, {
  // @note: `touch` feature workaround
  // cf. http://www.stucox.com/blog/you-cant-detect-a-touchscreen/
  id: 'mobile-device',
  check: function check() {
    return _client2.default.platform.isMobile;
  }
}, {
  id: 'audio-input',
  check: function check() {
    return !!navigator.getUserMedia;
  },
  startHook: function startHook() {
    navigator.getUserMedia({ audio: true }, function (stream) {
      stream.getAudioTracks()[0].stop();
    }, function (err) {
      throw err;
    });
  }
}, {
  id: 'full-screen',
  check: function check() {
    // check later, is not a functionnality that can brake the application
    return true;
  },
  interactionHook: function interactionHook() {
    if (_screenfull2.default.enabled) _screenfull2.default.request();
  }
}];

var SERVICE_ID = 'service:platform';

/**
 * Interface for the client `'platform'` service.
 *
 * This services is responsible to give general informations about the user's
 * device (cf. [`client.device`]{@link module:soundworks/client.client.platform})
 * as well as check availability and provide hooks to initialize the features
 * required by the application (audio, microphone, etc.).
 * If one of the required definitions is not available, an view is created with
 * an error message and the [`client.compatible`]{@link module:soundworks/client.client.compatible}
 * attribute is set to `false`.
 *
 * Available built-in definitions are:
 * - 'web-audio'
 * - 'mobile-device'
 * - 'audio-input'
 * - 'full-screen' (this feature don't block the application, just applied if available)
 *
 * Most of these feature requiring an interaction or a confirmation from the
 * user in order to be initialized correctly, be carefull when setting
 * `showDialog` option to `false`.
 *
 * @see {@link module:soundworks/client.client}
 *
 * @param {Object} options
 * @param {Array<String>|String} options.features - Id(s) of the feature(s)
 *  required by the application.
 * @param {}
 *
 * @memberof module:soundworks/client
 * @example
 * // inside the experience constructor
 * this.platform = this.require('platform', { features: 'web-audio' });
 */

var Platform = function (_Service) {
  (0, _inherits3.default)(Platform, _Service);

  /** _<span class="warning">__WARNING__</span> This class should never be instanciated manually_ */

  function Platform() {
    (0, _classCallCheck3.default)(this, Platform);

    var _this = (0, _possibleConstructorReturn3.default)(this, (0, _getPrototypeOf2.default)(Platform).call(this, SERVICE_ID, false));

    var defaults = {
      // wakeLock: false, // @todo - fix and transform into a feature
      showDialog: true,
      viewCtor: _SegmentedView2.default,
      viewPriority: 10
    };

    _this.configure(defaults);

    _this._requiredFeatures = new _set2.default();
    _this._featureDefinitions = {};

    defaultDefinitions.forEach(function (def) {
      return _this.addFeatureDefinition(def);
    });
    return _this;
  }

  /** @private */


  (0, _createClass3.default)(Platform, [{
    key: 'configure',
    value: function configure(options) {
      if (options.features) {
        var features = options.features;

        if (typeof features === 'string') features = [features];

        this.requireFeature.apply(this, (0, _toConsumableArray3.default)(features));
        delete options.features;
      }

      (0, _get3.default)((0, _getPrototypeOf2.default)(Platform.prototype), 'configure', this).call(this, options);
    }

    /** @private */

  }, {
    key: 'init',
    value: function init() {
      this._defineAudioFileExtention();
      this._definePlatform();
      // resolve required features from the application
      _client2.default.compatible = this.resolveRequiredFeatures();
      this.viewContent.isCompatible = _client2.default.compatible;

      this.viewCtor = this.options.viewCtor;
      this.view = this.createView();
    }

    /** @private */

  }, {
    key: 'start',
    value: function start() {
      (0, _get3.default)((0, _getPrototypeOf2.default)(Platform.prototype), 'start', this).call(this);

      if (!this.hasStarted) this.init();

      // execute start hooks from the features definitions
      var startHooks = this.getStartHooks();
      startHooks.forEach(function (hook) {
        return hook();
      });

      // optionnaly skip the view if client is compatible
      if (_client2.default.compatible && !this.options.showDialog) {
        // bypass if features contains 'web-audio' and client.platform.os === 'ios'
        if (this._requiredFeatures.has('web-audio') && _client2.default.platform.os === 'ios') this.show();else this.ready();
      } else {
        this.show();
      }

      // install events for interaction hook
      if (_client2.default.compatible) {
        var event = _client2.default.platform.isMobile ? 'touchend' : 'click';
        this.view.installEvents((0, _defineProperty3.default)({}, event, this._onInteraction.bind(this)));
      }
    }

    /** @private */

  }, {
    key: 'stop',
    value: function stop() {
      this.hide();
      (0, _get3.default)((0, _getPrototypeOf2.default)(Platform.prototype), 'stop', this).call(this);
    }

    /**
     * Add a new feature definition or override an existing one.
     * @param {module:soundworks/client.Platform~definition} obj - Definition of
     *  the feature to add to the existing ones.
     */

  }, {
    key: 'addFeatureDefinition',
    value: function addFeatureDefinition(obj) {
      this._featureDefinitions[obj.id] = obj;
    }

    /**
     * Require features avalability for the application.
     * @private
     * @param {...String} features - The id(s) of the feature(s) to be required.
     */

  }, {
    key: 'requireFeature',
    value: function requireFeature() {
      var _this2 = this;

      for (var _len = arguments.length, features = Array(_len), _key = 0; _key < _len; _key++) {
        features[_key] = arguments[_key];
      }

      features.forEach(function (id) {
        return _this2._requiredFeatures.add(id);
      });
    }

    /**
     * Execute all `check` functions from the definition of the required features.
     * @private
     * @return {Boolean} - true if all checks pass, false otherwise.
     *
     */

  }, {
    key: 'resolveRequiredFeatures',
    value: function resolveRequiredFeatures() {
      var _this3 = this;

      var result = true;

      this._requiredFeatures.forEach(function (feature) {
        var checkFunction = _this3._featureDefinitions[feature].check;

        if (!(typeof checkFunction === 'function')) throw new Error('No check function defined for ' + feature + ' feature');

        result = result && checkFunction();
      });

      return result;
    }

    /**
     * Returns the list of the functions to be executed on `start` lifecycle.
     * @private
     * @return {Array}
     */

  }, {
    key: 'getStartHooks',
    value: function getStartHooks() {
      return this._getHooks('startHook');
    }

    /**
     * Returns the list of the functions to be executed when the user
     * interacts with the application for the first time.
     * @private
     * @return {Array}
     */

  }, {
    key: 'getInteractionHooks',
    value: function getInteractionHooks() {
      return this._getHooks('interactionHook');
    }

    /** @private */

  }, {
    key: '_getHooks',
    value: function _getHooks(type) {
      var _this4 = this;

      var hooks = [];

      this._requiredFeatures.forEach(function (feature) {
        var hook = _this4._featureDefinitions[feature][type];

        if (hook) hooks.push(hook);
      });

      return hooks;
    }

    /**
     * Execute `interactions` hooks from the `platform` service.
     * Also activate the media according to the `options`.
     * @private
     */

  }, {
    key: '_onInteraction',
    value: function _onInteraction() {
      // execute interaction hooks from the platform
      var interactionHooks = this.getInteractionHooks();
      interactionHooks.forEach(function (hook) {
        return hook();
      });

      // @todo - fix and transform into a feature
      // if (this.options.wakeLock)
      //   this._initWakeLock();

      this.ready();
    }

    /**
     * Populate `client.platform` with the prefered audio file extention for the platform.
     * @private
     */

  }, {
    key: '_defineAudioFileExtention',
    value: function _defineAudioFileExtention() {
      var a = document.createElement('audio');
      // http://diveintohtml5.info/everything.html
      if (!!(a.canPlayType && a.canPlayType('audio/mpeg;'))) {
        _client2.default.platform.audioFileExt = '.mp3';
      } else if (!!(a.canPlayType && a.canPlayType('audio/ogg; codecs="vorbis"'))) {
        _client2.default.platform.audioFileExt = '.ogg';
      } else {
        _client2.default.platform.audioFileExt = '.wav';
      }
    }

    /**
     * Populate `client.platform` with the os name.
     * @private
     */

  }, {
    key: '_definePlatform',
    value: function _definePlatform() {
      var ua = window.navigator.userAgent;
      var md = new _mobileDetect2.default(ua);

      _client2.default.platform.isMobile = md.mobile() !== null; // true if phone or tablet
      _client2.default.platform.os = function () {
        var os = md.os();

        if (os === 'AndroidOS') return 'android';else if (os === 'iOS') return 'ios';else return 'other';
      }();
    }

    // @todo - fix transform into feature definition
    // hacks to keep the device awake...
    // cf. https://github.com/borismus/webvr-boilerplate/blob/8abbc74cfa5976b9ab0c388cb0c51944008c6989/js/webvr-manager.js#L268-L289

  }, {
    key: '_initWakeLock',
    value: function _initWakeLock() {
      var _this5 = this;

      this._wakeLockVideo = document.createElement('video');

      this._wakeLockVideo.addEventListener('ended', function () {
        _this5._wakeLockVideo.play();
      });
    }
  }, {
    key: '_requestWakeLock',
    value: function _requestWakeLock() {
      var os = _client2.default.platform.os;
      this._releaseWakeClock();

      if (os === 'ios') {
        if (this._wakeLockTimer) return;

        this._wakeLockTimer = setInterval(function () {
          window.location = window.location;
          setTimeout(window.stop, 0);
        }, 30000);
      } else if (os === 'android') {
        if (this._wakeLockVideo.paused === false) return;

        this._wakeLockVideo.src = _base64('video/webm', 'GkXfowEAAAAAAAAfQoaBAUL3gQFC8oEEQvOBCEKChHdlYm1Ch4ECQoWBAhhTgGcBAAAAAAACWxFNm3RALE27i1OrhBVJqWZTrIHfTbuMU6uEFlSua1OsggEuTbuMU6uEHFO7a1OsggI+7AEAAAAAAACkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVSalmAQAAAAAAAEMq17GDD0JATYCMTGF2ZjU2LjQuMTAxV0GMTGF2ZjU2LjQuMTAxc6SQ20Yv/Elws73A/+KfEjM11ESJiEBkwAAAAAAAFlSuawEAAAAAAABHrgEAAAAAAAA+14EBc8WBAZyBACK1nIN1bmSGhVZfVlA4g4EBI+ODhAT3kNXgAQAAAAAAABKwgRC6gRBTwIEBVLCBEFS6gRAfQ7Z1AQAAAAAAALHngQCgAQAAAAAAAFyho4EAAIAQAgCdASoQABAAAEcIhYWIhYSIAgIADA1gAP7/q1CAdaEBAAAAAAAALaYBAAAAAAAAJO6BAaWfEAIAnQEqEAAQAABHCIWFiIWEiAICAAwNYAD+/7r/QKABAAAAAAAAQKGVgQBTALEBAAEQEAAYABhYL/QACAAAdaEBAAAAAAAAH6YBAAAAAAAAFu6BAaWRsQEAARAQABgAGFgv9AAIAAAcU7trAQAAAAAAABG7j7OBALeK94EB8YIBgfCBAw==');
        this._wakeLockVideo.play();
      }
    }
  }, {
    key: '_releaseWakeClock',
    value: function _releaseWakeClock() {
      var os = _client2.default.platform.os;

      if (os === 'ios') {
        if (this._wakeLockTimer) {
          clearInterval(this._wakeLockTimer);
          this._wakeLockTimer = null;
        }
      } else if (os === 'android') {
        this._wakeLockVideo.pause();
        this._wakeLockVideo.src = '';
      }
    }
  }]);
  return Platform;
}(_Service3.default);

_serviceManager2.default.register(SERVICE_ID, Platform);

exports.default = Platform;
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIlBsYXRmb3JtLmpzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQUFBOztBQUNBOzs7O0FBQ0E7Ozs7QUFDQTs7OztBQUNBOzs7O0FBQ0E7Ozs7QUFDQTs7OztBQUVBOztJQUFZOzs7Ozs7QUFDWixRQUFRLFVBQVIsQ0FBbUIsSUFBbkI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQW1CQSxJQUFNLHFCQUFxQixDQUN6QjtBQUNFLE1BQUksV0FBSjtBQUNBLFNBQU8saUJBQVc7QUFDaEIsV0FBTyxDQUFDLHlCQUFELENBRFM7R0FBWDtBQUdQLG1CQUFpQiwyQkFBVztBQUMxQixRQUFJLENBQUMsaUJBQU8sUUFBUCxDQUFnQixRQUFoQixFQUNILE9BREY7O0FBR0EsUUFBTSxJQUFJLHlCQUFhLFVBQWIsRUFBSixDQUpvQjtBQUsxQixNQUFFLE9BQUYsQ0FBVSx5QkFBYSxXQUFiLENBQVYsQ0FMMEI7QUFNMUIsTUFBRSxJQUFGLENBQU8sS0FBUCxHQUFlLFdBQWY7O0FBTjBCLFFBUXBCLElBQUkseUJBQWEsZ0JBQWIsRUFBSixDQVJvQjtBQVMxQixNQUFFLE9BQUYsQ0FBVSxDQUFWLEVBVDBCO0FBVTFCLE1BQUUsU0FBRixDQUFZLEtBQVosR0FBb0IsRUFBcEIsQ0FWMEI7QUFXMUIsTUFBRSxLQUFGLENBQVEsQ0FBUjs7O0FBWDBCLFFBY3RCLGlCQUFPLFFBQVAsQ0FBZ0IsRUFBaEIsS0FBdUIsU0FBdkIsRUFDRixFQUFFLElBQUYsQ0FBTyx5QkFBYSxXQUFiLEdBQTJCLElBQTNCLENBQVAsQ0FERjtHQWRlO0NBTk0sRUF3QnpCOzs7QUFHRSxNQUFJLGVBQUo7QUFDQSxTQUFPLGlCQUFXO0FBQ2hCLFdBQU8saUJBQU8sUUFBUCxDQUFnQixRQUFoQixDQURTO0dBQVg7Q0E1QmdCLEVBZ0N6QjtBQUNFLE1BQUksYUFBSjtBQUNBLFNBQU8saUJBQVc7QUFDaEIsV0FBTyxDQUFDLENBQUMsVUFBVSxZQUFWLENBRE87R0FBWDtBQUdQLGFBQVcscUJBQVc7QUFDcEIsY0FBVSxZQUFWLENBQXVCLEVBQUUsT0FBTyxJQUFQLEVBQXpCLEVBQXdDLFVBQVMsTUFBVCxFQUFpQjtBQUN2RCxhQUFPLGNBQVAsR0FBd0IsQ0FBeEIsRUFBMkIsSUFBM0IsR0FEdUQ7S0FBakIsRUFFckMsVUFBVSxHQUFWLEVBQWU7QUFDaEIsWUFBTSxHQUFOLENBRGdCO0tBQWYsQ0FGSCxDQURvQjtHQUFYO0NBckNZLEVBNkN6QjtBQUNFLE1BQUksYUFBSjtBQUNBLFNBQU8saUJBQVc7O0FBRWhCLFdBQU8sSUFBUCxDQUZnQjtHQUFYO0FBSVAsOENBQWtCO0FBQ2hCLFFBQUkscUJBQVcsT0FBWCxFQUNGLHFCQUFXLE9BQVgsR0FERjtHQVBKO0NBN0N5QixDQUFyQjs7QUEyRE4sSUFBTSxhQUFhLGtCQUFiOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUFtQ0E7Ozs7O0FBRUosV0FGSSxRQUVKLEdBQWM7d0NBRlYsVUFFVTs7NkZBRlYscUJBR0ksWUFBWSxRQUROOztBQUdaLFFBQU0sV0FBVzs7QUFFZixrQkFBWSxJQUFaO0FBQ0EsdUNBSGU7QUFJZixvQkFBYyxFQUFkO0tBSkksQ0FITTs7QUFVWixVQUFLLFNBQUwsQ0FBZSxRQUFmLEVBVlk7O0FBWVosVUFBSyxpQkFBTCxHQUF5QixtQkFBekIsQ0FaWTtBQWFaLFVBQUssbUJBQUwsR0FBMkIsRUFBM0IsQ0FiWTs7QUFlWix1QkFBbUIsT0FBbkIsQ0FBMkIsVUFBQyxHQUFEO2FBQVMsTUFBSyxvQkFBTCxDQUEwQixHQUExQjtLQUFULENBQTNCLENBZlk7O0dBQWQ7Ozs7OzZCQUZJOzs4QkFxQk0sU0FBUztBQUNqQixVQUFJLFFBQVEsUUFBUixFQUFrQjtBQUNwQixZQUFJLFdBQVcsUUFBUSxRQUFSLENBREs7O0FBR3BCLFlBQUksT0FBTyxRQUFQLEtBQW9CLFFBQXBCLEVBQ0YsV0FBVyxDQUFDLFFBQUQsQ0FBWCxDQURGOztBQUdBLGFBQUssY0FBTCw4Q0FBdUIsU0FBdkIsRUFOb0I7QUFPcEIsZUFBTyxRQUFRLFFBQVIsQ0FQYTtPQUF0Qjs7QUFVQSx1REFoQ0UsbURBZ0NjLFFBQWhCLENBWGlCOzs7Ozs7OzJCQWVaO0FBQ0wsV0FBSyx5QkFBTCxHQURLO0FBRUwsV0FBSyxlQUFMOztBQUZLLHNCQUlMLENBQU8sVUFBUCxHQUFvQixLQUFLLHVCQUFMLEVBQXBCLENBSks7QUFLTCxXQUFLLFdBQUwsQ0FBaUIsWUFBakIsR0FBZ0MsaUJBQU8sVUFBUCxDQUwzQjs7QUFPTCxXQUFLLFFBQUwsR0FBZ0IsS0FBSyxPQUFMLENBQWEsUUFBYixDQVBYO0FBUUwsV0FBSyxJQUFMLEdBQVksS0FBSyxVQUFMLEVBQVosQ0FSSzs7Ozs7Ozs0QkFZQztBQUNOLHVEQWpERSw4Q0FpREYsQ0FETTs7QUFHTixVQUFJLENBQUMsS0FBSyxVQUFMLEVBQ0gsS0FBSyxJQUFMLEdBREY7OztBQUhNLFVBT0EsYUFBYSxLQUFLLGFBQUwsRUFBYixDQVBBO0FBUU4saUJBQVcsT0FBWCxDQUFtQixVQUFDLElBQUQ7ZUFBVTtPQUFWLENBQW5COzs7QUFSTSxVQVdGLGlCQUFPLFVBQVAsSUFBcUIsQ0FBQyxLQUFLLE9BQUwsQ0FBYSxVQUFiLEVBQXlCOztBQUVqRCxZQUFJLEtBQUssaUJBQUwsQ0FBdUIsR0FBdkIsQ0FBMkIsV0FBM0IsS0FBMkMsaUJBQU8sUUFBUCxDQUFnQixFQUFoQixLQUF1QixLQUF2QixFQUM3QyxLQUFLLElBQUwsR0FERixLQUdFLEtBQUssS0FBTCxHQUhGO09BRkYsTUFNTztBQUNMLGFBQUssSUFBTCxHQURLO09BTlA7OztBQVhNLFVBc0JGLGlCQUFPLFVBQVAsRUFBbUI7QUFDckIsWUFBTSxRQUFRLGlCQUFPLFFBQVAsQ0FBZ0IsUUFBaEIsR0FBMkIsVUFBM0IsR0FBd0MsT0FBeEMsQ0FETztBQUVyQixhQUFLLElBQUwsQ0FBVSxhQUFWLG1DQUEyQixPQUFRLEtBQUssY0FBTCxDQUFvQixJQUFwQixDQUF5QixJQUF6QixFQUFuQyxFQUZxQjtPQUF2Qjs7Ozs7OzsyQkFPSztBQUNMLFdBQUssSUFBTCxHQURLO0FBRUwsdURBL0VFLDZDQStFRixDQUZLOzs7Ozs7Ozs7Ozt5Q0FVYyxLQUFLO0FBQ3hCLFdBQUssbUJBQUwsQ0FBeUIsSUFBSSxFQUFKLENBQXpCLEdBQW1DLEdBQW5DLENBRHdCOzs7Ozs7Ozs7OztxQ0FTRTs7O3dDQUFWOztPQUFVOztBQUMxQixlQUFTLE9BQVQsQ0FBaUIsVUFBQyxFQUFEO2VBQVEsT0FBSyxpQkFBTCxDQUF1QixHQUF2QixDQUEyQixFQUEzQjtPQUFSLENBQWpCLENBRDBCOzs7Ozs7Ozs7Ozs7OENBVUY7OztBQUN4QixVQUFJLFNBQVMsSUFBVCxDQURvQjs7QUFHeEIsV0FBSyxpQkFBTCxDQUF1QixPQUF2QixDQUErQixVQUFDLE9BQUQsRUFBYTtBQUMxQyxZQUFNLGdCQUFnQixPQUFLLG1CQUFMLENBQXlCLE9BQXpCLEVBQWtDLEtBQWxDLENBRG9COztBQUcxQyxZQUFJLEVBQUUsT0FBTyxhQUFQLEtBQXlCLFVBQXpCLENBQUYsRUFDRixNQUFNLElBQUksS0FBSixvQ0FBMkMsb0JBQTNDLENBQU4sQ0FERjs7QUFHQSxpQkFBUyxVQUFVLGVBQVYsQ0FOaUM7T0FBYixDQUEvQixDQUh3Qjs7QUFZeEIsYUFBTyxNQUFQLENBWndCOzs7Ozs7Ozs7OztvQ0FvQlY7QUFDZCxhQUFPLEtBQUssU0FBTCxDQUFlLFdBQWYsQ0FBUCxDQURjOzs7Ozs7Ozs7Ozs7MENBVU07QUFDcEIsYUFBTyxLQUFLLFNBQUwsQ0FBZSxpQkFBZixDQUFQLENBRG9COzs7Ozs7OzhCQUtaLE1BQU07OztBQUNkLFVBQU0sUUFBUSxFQUFSLENBRFE7O0FBR2QsV0FBSyxpQkFBTCxDQUF1QixPQUF2QixDQUErQixVQUFDLE9BQUQsRUFBYTtBQUMxQyxZQUFNLE9BQU8sT0FBSyxtQkFBTCxDQUF5QixPQUF6QixFQUFrQyxJQUFsQyxDQUFQLENBRG9DOztBQUcxQyxZQUFJLElBQUosRUFDRSxNQUFNLElBQU4sQ0FBVyxJQUFYLEVBREY7T0FINkIsQ0FBL0IsQ0FIYzs7QUFVZCxhQUFPLEtBQVAsQ0FWYzs7Ozs7Ozs7Ozs7cUNBa0JDOztBQUVmLFVBQU0sbUJBQW1CLEtBQUssbUJBQUwsRUFBbkIsQ0FGUztBQUdmLHVCQUFpQixPQUFqQixDQUF5QixVQUFDLElBQUQ7ZUFBVTtPQUFWLENBQXpCOzs7Ozs7QUFIZSxVQVNmLENBQUssS0FBTCxHQVRlOzs7Ozs7Ozs7O2dEQWdCVztBQUMxQixVQUFNLElBQUksU0FBUyxhQUFULENBQXVCLE9BQXZCLENBQUo7O0FBRG9CLFVBR3RCLENBQUMsRUFBRSxFQUFFLFdBQUYsSUFBaUIsRUFBRSxXQUFGLENBQWMsYUFBZCxDQUFqQixDQUFGLEVBQWtEO0FBQ3JELHlCQUFPLFFBQVAsQ0FBZ0IsWUFBaEIsR0FBK0IsTUFBL0IsQ0FEcUQ7T0FBdkQsTUFFTyxJQUFJLENBQUMsRUFBRSxFQUFFLFdBQUYsSUFBaUIsRUFBRSxXQUFGLENBQWMsNEJBQWQsQ0FBakIsQ0FBRixFQUFpRTtBQUMzRSx5QkFBTyxRQUFQLENBQWdCLFlBQWhCLEdBQStCLE1BQS9CLENBRDJFO09BQXRFLE1BRUE7QUFDTCx5QkFBTyxRQUFQLENBQWdCLFlBQWhCLEdBQStCLE1BQS9CLENBREs7T0FGQTs7Ozs7Ozs7OztzQ0FXUztBQUNoQixVQUFNLEtBQUssT0FBTyxTQUFQLENBQWlCLFNBQWpCLENBREs7QUFFaEIsVUFBTSxLQUFLLDJCQUFpQixFQUFqQixDQUFMLENBRlU7O0FBSWhCLHVCQUFPLFFBQVAsQ0FBZ0IsUUFBaEIsR0FBNEIsR0FBRyxNQUFILE9BQWdCLElBQWhCO0FBSlosc0JBS2hCLENBQU8sUUFBUCxDQUFnQixFQUFoQixHQUFxQixZQUFZO0FBQy9CLFlBQU0sS0FBSyxHQUFHLEVBQUgsRUFBTCxDQUR5Qjs7QUFHL0IsWUFBSSxPQUFPLFdBQVAsRUFDRixPQUFPLFNBQVAsQ0FERixLQUVLLElBQUksT0FBTyxLQUFQLEVBQ1AsT0FBTyxLQUFQLENBREcsS0FHSCxPQUFPLE9BQVAsQ0FIRztPQUxlLEVBQXRCLENBTGdCOzs7Ozs7Ozs7b0NBb0JGOzs7QUFDZCxXQUFLLGNBQUwsR0FBc0IsU0FBUyxhQUFULENBQXVCLE9BQXZCLENBQXRCLENBRGM7O0FBR2QsV0FBSyxjQUFMLENBQW9CLGdCQUFwQixDQUFxQyxPQUFyQyxFQUE4QyxZQUFNO0FBQ2xELGVBQUssY0FBTCxDQUFvQixJQUFwQixHQURrRDtPQUFOLENBQTlDLENBSGM7Ozs7dUNBUUc7QUFDakIsVUFBTSxLQUFLLGlCQUFPLFFBQVAsQ0FBZ0IsRUFBaEIsQ0FETTtBQUVqQixXQUFLLGlCQUFMLEdBRmlCOztBQUlqQixVQUFJLE9BQU8sS0FBUCxFQUFjO0FBQ2hCLFlBQUksS0FBSyxjQUFMLEVBQXFCLE9BQXpCOztBQUVBLGFBQUssY0FBTCxHQUFzQixZQUFZLFlBQU07QUFDdEMsaUJBQU8sUUFBUCxHQUFrQixPQUFPLFFBQVAsQ0FEb0I7QUFFdEMscUJBQVcsT0FBTyxJQUFQLEVBQWEsQ0FBeEIsRUFGc0M7U0FBTixFQUcvQixLQUhtQixDQUF0QixDQUhnQjtPQUFsQixNQU9PLElBQUksT0FBTyxTQUFQLEVBQWtCO0FBQzNCLFlBQUksS0FBSyxjQUFMLENBQW9CLE1BQXBCLEtBQStCLEtBQS9CLEVBQXNDLE9BQTFDOztBQUVBLGFBQUssY0FBTCxDQUFvQixHQUFwQixHQUEwQixRQUFRLFlBQVIsRUFBc0IsazNCQUF0QixDQUExQixDQUgyQjtBQUkzQixhQUFLLGNBQUwsQ0FBb0IsSUFBcEIsR0FKMkI7T0FBdEI7Ozs7d0NBUVc7QUFDbEIsVUFBTSxLQUFLLGlCQUFPLFFBQVAsQ0FBZ0IsRUFBaEIsQ0FETzs7QUFHbEIsVUFBSSxPQUFPLEtBQVAsRUFBYztBQUNoQixZQUFJLEtBQUssY0FBTCxFQUFxQjtBQUN2Qix3QkFBYyxLQUFLLGNBQUwsQ0FBZCxDQUR1QjtBQUV2QixlQUFLLGNBQUwsR0FBc0IsSUFBdEIsQ0FGdUI7U0FBekI7T0FERixNQUtPLElBQUksT0FBTyxTQUFQLEVBQWtCO0FBQzNCLGFBQUssY0FBTCxDQUFvQixLQUFwQixHQUQyQjtBQUUzQixhQUFLLGNBQUwsQ0FBb0IsR0FBcEIsR0FBMEIsRUFBMUIsQ0FGMkI7T0FBdEI7OztTQXRQTDs7O0FBNlBOLHlCQUFlLFFBQWYsQ0FBd0IsVUFBeEIsRUFBb0MsUUFBcEM7O2tCQUVlIiwiZmlsZSI6IlBsYXRmb3JtLmpzIiwic291cmNlc0NvbnRlbnQiOlsiaW1wb3J0IHsgYXVkaW9Db250ZXh0IH0gZnJvbSAnd2F2ZXMtYXVkaW8nO1xuaW1wb3J0IGNsaWVudCBmcm9tICcuLi9jb3JlL2NsaWVudCc7XG5pbXBvcnQgTW9iaWxlRGV0ZWN0IGZyb20gJ21vYmlsZS1kZXRlY3QnO1xuaW1wb3J0IHNjcmVlbmZ1bGwgZnJvbSAnc2NyZWVuZnVsbCc7XG5pbXBvcnQgU2VnbWVudGVkVmlldyBmcm9tICcuLi92aWV3cy9TZWdtZW50ZWRWaWV3JztcbmltcG9ydCBTZXJ2aWNlIGZyb20gJy4uL2NvcmUvU2VydmljZSc7XG5pbXBvcnQgc2VydmljZU1hbmFnZXIgZnJvbSAnLi4vY29yZS9zZXJ2aWNlTWFuYWdlcic7XG4vLyBAdG9kbyAtIGRlZmluZSBpZiB3ZSBrZWVwIHRoaXMgaW4gZGVmYXVsdHNcbmltcG9ydCAqIGFzIGFkYXB0ZXIgZnJvbSAnd2VicnRjLWFkYXB0ZXInO1xuYWRhcHRlci5kaXNhYmxlTG9nKHRydWUpO1xuXG4vLyBAdG9kbyAtIHRvIGJlIGFkZGVkXG4vLyArIOKAnHZpZGVvLWlucHV04oCdOiBuZWVkcyB2aWRlbyBpbnB1dFxuLy8gKyDigJx2aWRlby1hdWRpby1pbnB1dOKAnTogbmVlZHMgdmlkZW8gaW5wdXRcbi8vICsgRGV2aWNlTW90aW9uL09yaWVudGF0aW9uIGNvbmRpdGlvbnMgZ2VuZXJhdGVkIGJ5IHRoZSBtb3Rpb24taW5wdXQgbW9kdWxlXG5cbi8qKlxuICogU3RydWN0dXJlIG9mIHRoZSBkZWZpbml0aW9uIG9mIGEgZmVhdHVyZSB0byBiZSB0ZXN0ZWQuXG4gKiBAdHlwZWRlZiB7T2JqZWN0fSBtb2R1bGU6c291bmR3b3Jrcy9jbGllbnQuUGxhdGZvcm1+ZGVmaW5pdGlvblxuICogQHByb3BlcnR5IHtTdHJpbmd9IGlkIC0gSWQgb2YgdGhlIGRlZmluaXRpb24uXG4gKiBAcHJvcGVydHkge0Z1bmN0aW9ufSBjaGVjayAtIEEgZnVuY3Rpb24gdGhhdCBzaG91bGQgcmV0dXJuIGB0cnVlYCBpZiB0aGVcbiAqICBmZWF0dXJlIGlzIGF2YWlsYWJsZSBvbiB0aGUgcGxhdGZvcm0sIGBmYWxzZWAgb3RoZXJ3aXNlLlxuICogQHByb3BlcnR5IHtGdW5jdGlvbn0gW2ludGVyYWN0aW9uSG9va10gLSBBIGZ1bmN0aW9uIHRvIGJlIGV4ZWN1dGVkIG9uIHRoZVxuICogIGZpcnN0IGludGVyYWN0aW9uIChpLmUuIGBjbGlja2Agb3IgYHRvdWNoc3RhcnRgKSBvZiB0aGUgdXNlciB3aXRoIGFwcGxpY2F0aW9uXG4gKiAgKGZvciBleGFtcGxlLCB0byBpbml0aWFsaXplIEF1ZGlvQ29udGV4dCBvbiBpT1MgZGV2aWNlcykuXG4gKiBAcHJvcGVydHkge0Z1bmN0aW9ufSBbaW50ZXJhY3Rpb25Ib29rXSAtIEEgZnVuY3Rpb24gdG8gYmUgZXhlY3V0ZWQgb24gc3RhcnRcbiAqICAoZm9yIGV4YW1wbGUgdG8gYXNrIGFjY2VzcyB0byBtaWNyb3Bob25lIG9yIGdlb2xvY2F0aW9uKS5cbiAqL1xuY29uc3QgZGVmYXVsdERlZmluaXRpb25zID0gW1xuICB7XG4gICAgaWQ6ICd3ZWItYXVkaW8nLFxuICAgIGNoZWNrOiBmdW5jdGlvbigpIHtcbiAgICAgIHJldHVybiAhIWF1ZGlvQ29udGV4dDtcbiAgICB9LFxuICAgIGludGVyYWN0aW9uSG9vazogZnVuY3Rpb24oKSB7XG4gICAgICBpZiAoIWNsaWVudC5wbGF0Zm9ybS5pc01vYmlsZSlcbiAgICAgICAgcmV0dXJuO1xuXG4gICAgICBjb25zdCBnID0gYXVkaW9Db250ZXh0LmNyZWF0ZUdhaW4oKTtcbiAgICAgIGcuY29ubmVjdChhdWRpb0NvbnRleHQuZGVzdGluYXRpb24pO1xuICAgICAgZy5nYWluLnZhbHVlID0gMC4wMDAwMDAwMDE7IC8vIC0xODBkQiA/XG5cbiAgICAgIGNvbnN0IG8gPSBhdWRpb0NvbnRleHQuY3JlYXRlT3NjaWxsYXRvcigpO1xuICAgICAgby5jb25uZWN0KGcpO1xuICAgICAgby5mcmVxdWVuY3kudmFsdWUgPSAyMDtcbiAgICAgIG8uc3RhcnQoMCk7XG5cbiAgICAgIC8vIHByZXZlbnQgYW5kcm9pZCB0byBzdG9wIGF1ZGlvIGJ5IGtlcGluZyB0aGUgb3NjaWxsYXRvciBhY3RpdmVcbiAgICAgIGlmIChjbGllbnQucGxhdGZvcm0ub3MgIT09ICdhbmRyb2lkJylcbiAgICAgICAgby5zdG9wKGF1ZGlvQ29udGV4dC5jdXJyZW50VGltZSArIDAuMDEpO1xuICAgIH1cbiAgfSxcbiAge1xuICAgIC8vIEBub3RlOiBgdG91Y2hgIGZlYXR1cmUgd29ya2Fyb3VuZFxuICAgIC8vIGNmLiBodHRwOi8vd3d3LnN0dWNveC5jb20vYmxvZy95b3UtY2FudC1kZXRlY3QtYS10b3VjaHNjcmVlbi9cbiAgICBpZDogJ21vYmlsZS1kZXZpY2UnLFxuICAgIGNoZWNrOiBmdW5jdGlvbigpIHtcbiAgICAgIHJldHVybiBjbGllbnQucGxhdGZvcm0uaXNNb2JpbGU7XG4gICAgfVxuICB9LFxuICB7XG4gICAgaWQ6ICdhdWRpby1pbnB1dCcsXG4gICAgY2hlY2s6IGZ1bmN0aW9uKCkge1xuICAgICAgcmV0dXJuICEhbmF2aWdhdG9yLmdldFVzZXJNZWRpYTtcbiAgICB9LFxuICAgIHN0YXJ0SG9vazogZnVuY3Rpb24oKSB7XG4gICAgICBuYXZpZ2F0b3IuZ2V0VXNlck1lZGlhKHsgYXVkaW86IHRydWUgfSwgZnVuY3Rpb24oc3RyZWFtKSB7XG4gICAgICAgIHN0cmVhbS5nZXRBdWRpb1RyYWNrcygpWzBdLnN0b3AoKTtcbiAgICAgIH0sIGZ1bmN0aW9uIChlcnIpIHtcbiAgICAgICAgdGhyb3cgZXJyO1xuICAgICAgfSk7XG4gICAgfVxuICB9LFxuICB7XG4gICAgaWQ6ICdmdWxsLXNjcmVlbicsXG4gICAgY2hlY2s6IGZ1bmN0aW9uKCkge1xuICAgICAgLy8gY2hlY2sgbGF0ZXIsIGlzIG5vdCBhIGZ1bmN0aW9ubmFsaXR5IHRoYXQgY2FuIGJyYWtlIHRoZSBhcHBsaWNhdGlvblxuICAgICAgcmV0dXJuIHRydWU7XG4gICAgfSxcbiAgICBpbnRlcmFjdGlvbkhvb2soKSB7XG4gICAgICBpZiAoc2NyZWVuZnVsbC5lbmFibGVkKVxuICAgICAgICBzY3JlZW5mdWxsLnJlcXVlc3QoKTtcbiAgICB9XG4gIH1cbl07XG5cblxuY29uc3QgU0VSVklDRV9JRCA9ICdzZXJ2aWNlOnBsYXRmb3JtJztcblxuLyoqXG4gKiBJbnRlcmZhY2UgZm9yIHRoZSBjbGllbnQgYCdwbGF0Zm9ybSdgIHNlcnZpY2UuXG4gKlxuICogVGhpcyBzZXJ2aWNlcyBpcyByZXNwb25zaWJsZSB0byBnaXZlIGdlbmVyYWwgaW5mb3JtYXRpb25zIGFib3V0IHRoZSB1c2VyJ3NcbiAqIGRldmljZSAoY2YuIFtgY2xpZW50LmRldmljZWBde0BsaW5rIG1vZHVsZTpzb3VuZHdvcmtzL2NsaWVudC5jbGllbnQucGxhdGZvcm19KVxuICogYXMgd2VsbCBhcyBjaGVjayBhdmFpbGFiaWxpdHkgYW5kIHByb3ZpZGUgaG9va3MgdG8gaW5pdGlhbGl6ZSB0aGUgZmVhdHVyZXNcbiAqIHJlcXVpcmVkIGJ5IHRoZSBhcHBsaWNhdGlvbiAoYXVkaW8sIG1pY3JvcGhvbmUsIGV0Yy4pLlxuICogSWYgb25lIG9mIHRoZSByZXF1aXJlZCBkZWZpbml0aW9ucyBpcyBub3QgYXZhaWxhYmxlLCBhbiB2aWV3IGlzIGNyZWF0ZWQgd2l0aFxuICogYW4gZXJyb3IgbWVzc2FnZSBhbmQgdGhlIFtgY2xpZW50LmNvbXBhdGlibGVgXXtAbGluayBtb2R1bGU6c291bmR3b3Jrcy9jbGllbnQuY2xpZW50LmNvbXBhdGlibGV9XG4gKiBhdHRyaWJ1dGUgaXMgc2V0IHRvIGBmYWxzZWAuXG4gKlxuICogQXZhaWxhYmxlIGJ1aWx0LWluIGRlZmluaXRpb25zIGFyZTpcbiAqIC0gJ3dlYi1hdWRpbydcbiAqIC0gJ21vYmlsZS1kZXZpY2UnXG4gKiAtICdhdWRpby1pbnB1dCdcbiAqIC0gJ2Z1bGwtc2NyZWVuJyAodGhpcyBmZWF0dXJlIGRvbid0IGJsb2NrIHRoZSBhcHBsaWNhdGlvbiwganVzdCBhcHBsaWVkIGlmIGF2YWlsYWJsZSlcbiAqXG4gKiBNb3N0IG9mIHRoZXNlIGZlYXR1cmUgcmVxdWlyaW5nIGFuIGludGVyYWN0aW9uIG9yIGEgY29uZmlybWF0aW9uIGZyb20gdGhlXG4gKiB1c2VyIGluIG9yZGVyIHRvIGJlIGluaXRpYWxpemVkIGNvcnJlY3RseSwgYmUgY2FyZWZ1bGwgd2hlbiBzZXR0aW5nXG4gKiBgc2hvd0RpYWxvZ2Agb3B0aW9uIHRvIGBmYWxzZWAuXG4gKlxuICogQHNlZSB7QGxpbmsgbW9kdWxlOnNvdW5kd29ya3MvY2xpZW50LmNsaWVudH1cbiAqXG4gKiBAcGFyYW0ge09iamVjdH0gb3B0aW9uc1xuICogQHBhcmFtIHtBcnJheTxTdHJpbmc+fFN0cmluZ30gb3B0aW9ucy5mZWF0dXJlcyAtIElkKHMpIG9mIHRoZSBmZWF0dXJlKHMpXG4gKiAgcmVxdWlyZWQgYnkgdGhlIGFwcGxpY2F0aW9uLlxuICogQHBhcmFtIHt9XG4gKlxuICogQG1lbWJlcm9mIG1vZHVsZTpzb3VuZHdvcmtzL2NsaWVudFxuICogQGV4YW1wbGVcbiAqIC8vIGluc2lkZSB0aGUgZXhwZXJpZW5jZSBjb25zdHJ1Y3RvclxuICogdGhpcy5wbGF0Zm9ybSA9IHRoaXMucmVxdWlyZSgncGxhdGZvcm0nLCB7IGZlYXR1cmVzOiAnd2ViLWF1ZGlvJyB9KTtcbiAqL1xuY2xhc3MgUGxhdGZvcm0gZXh0ZW5kcyBTZXJ2aWNlIHtcbiAgLyoqIF88c3BhbiBjbGFzcz1cIndhcm5pbmdcIj5fX1dBUk5JTkdfXzwvc3Bhbj4gVGhpcyBjbGFzcyBzaG91bGQgbmV2ZXIgYmUgaW5zdGFuY2lhdGVkIG1hbnVhbGx5XyAqL1xuICBjb25zdHJ1Y3RvcigpIHtcbiAgICBzdXBlcihTRVJWSUNFX0lELCBmYWxzZSk7XG5cbiAgICBjb25zdCBkZWZhdWx0cyA9IHtcbiAgICAgIC8vIHdha2VMb2NrOiBmYWxzZSwgLy8gQHRvZG8gLSBmaXggYW5kIHRyYW5zZm9ybSBpbnRvIGEgZmVhdHVyZVxuICAgICAgc2hvd0RpYWxvZzogdHJ1ZSxcbiAgICAgIHZpZXdDdG9yOiBTZWdtZW50ZWRWaWV3LFxuICAgICAgdmlld1ByaW9yaXR5OiAxMCxcbiAgICB9O1xuXG4gICAgdGhpcy5jb25maWd1cmUoZGVmYXVsdHMpO1xuXG4gICAgdGhpcy5fcmVxdWlyZWRGZWF0dXJlcyA9IG5ldyBTZXQoKTtcbiAgICB0aGlzLl9mZWF0dXJlRGVmaW5pdGlvbnMgPSB7fTtcblxuICAgIGRlZmF1bHREZWZpbml0aW9ucy5mb3JFYWNoKChkZWYpID0+IHRoaXMuYWRkRmVhdHVyZURlZmluaXRpb24oZGVmKSk7XG4gIH1cblxuICAvKiogQHByaXZhdGUgKi9cbiAgY29uZmlndXJlKG9wdGlvbnMpIHtcbiAgICBpZiAob3B0aW9ucy5mZWF0dXJlcykge1xuICAgICAgbGV0IGZlYXR1cmVzID0gb3B0aW9ucy5mZWF0dXJlcztcblxuICAgICAgaWYgKHR5cGVvZiBmZWF0dXJlcyA9PT0gJ3N0cmluZycpXG4gICAgICAgIGZlYXR1cmVzID0gW2ZlYXR1cmVzXTtcblxuICAgICAgdGhpcy5yZXF1aXJlRmVhdHVyZSguLi5mZWF0dXJlcyk7XG4gICAgICBkZWxldGUgb3B0aW9ucy5mZWF0dXJlcztcbiAgICB9XG5cbiAgICBzdXBlci5jb25maWd1cmUob3B0aW9ucyk7XG4gIH1cblxuICAvKiogQHByaXZhdGUgKi9cbiAgaW5pdCgpIHtcbiAgICB0aGlzLl9kZWZpbmVBdWRpb0ZpbGVFeHRlbnRpb24oKTtcbiAgICB0aGlzLl9kZWZpbmVQbGF0Zm9ybSgpO1xuICAgIC8vIHJlc29sdmUgcmVxdWlyZWQgZmVhdHVyZXMgZnJvbSB0aGUgYXBwbGljYXRpb25cbiAgICBjbGllbnQuY29tcGF0aWJsZSA9IHRoaXMucmVzb2x2ZVJlcXVpcmVkRmVhdHVyZXMoKTtcbiAgICB0aGlzLnZpZXdDb250ZW50LmlzQ29tcGF0aWJsZSA9IGNsaWVudC5jb21wYXRpYmxlO1xuXG4gICAgdGhpcy52aWV3Q3RvciA9IHRoaXMub3B0aW9ucy52aWV3Q3RvcjtcbiAgICB0aGlzLnZpZXcgPSB0aGlzLmNyZWF0ZVZpZXcoKTtcbiAgfVxuXG4gIC8qKiBAcHJpdmF0ZSAqL1xuICBzdGFydCgpIHtcbiAgICBzdXBlci5zdGFydCgpO1xuXG4gICAgaWYgKCF0aGlzLmhhc1N0YXJ0ZWQpXG4gICAgICB0aGlzLmluaXQoKTtcblxuICAgIC8vIGV4ZWN1dGUgc3RhcnQgaG9va3MgZnJvbSB0aGUgZmVhdHVyZXMgZGVmaW5pdGlvbnNcbiAgICBjb25zdCBzdGFydEhvb2tzID0gdGhpcy5nZXRTdGFydEhvb2tzKCk7XG4gICAgc3RhcnRIb29rcy5mb3JFYWNoKChob29rKSA9PiBob29rKCkpO1xuXG4gICAgLy8gb3B0aW9ubmFseSBza2lwIHRoZSB2aWV3IGlmIGNsaWVudCBpcyBjb21wYXRpYmxlXG4gICAgaWYgKGNsaWVudC5jb21wYXRpYmxlICYmICF0aGlzLm9wdGlvbnMuc2hvd0RpYWxvZykge1xuICAgICAgLy8gYnlwYXNzIGlmIGZlYXR1cmVzIGNvbnRhaW5zICd3ZWItYXVkaW8nIGFuZCBjbGllbnQucGxhdGZvcm0ub3MgPT09ICdpb3MnXG4gICAgICBpZiAodGhpcy5fcmVxdWlyZWRGZWF0dXJlcy5oYXMoJ3dlYi1hdWRpbycpICYmIGNsaWVudC5wbGF0Zm9ybS5vcyA9PT0gJ2lvcycpXG4gICAgICAgIHRoaXMuc2hvdygpO1xuICAgICAgZWxzZVxuICAgICAgICB0aGlzLnJlYWR5KCk7XG4gICAgfSBlbHNlIHtcbiAgICAgIHRoaXMuc2hvdygpO1xuICAgIH1cblxuICAgIC8vIGluc3RhbGwgZXZlbnRzIGZvciBpbnRlcmFjdGlvbiBob29rXG4gICAgaWYgKGNsaWVudC5jb21wYXRpYmxlKSB7XG4gICAgICBjb25zdCBldmVudCA9IGNsaWVudC5wbGF0Zm9ybS5pc01vYmlsZSA/ICd0b3VjaGVuZCcgOiAnY2xpY2snO1xuICAgICAgdGhpcy52aWV3Lmluc3RhbGxFdmVudHMoeyBbZXZlbnRdOiB0aGlzLl9vbkludGVyYWN0aW9uLmJpbmQodGhpcykgfSk7XG4gICAgfVxuICB9XG5cbiAgLyoqIEBwcml2YXRlICovXG4gIHN0b3AoKSB7XG4gICAgdGhpcy5oaWRlKCk7XG4gICAgc3VwZXIuc3RvcCgpO1xuICB9XG5cbiAgLyoqXG4gICAqIEFkZCBhIG5ldyBmZWF0dXJlIGRlZmluaXRpb24gb3Igb3ZlcnJpZGUgYW4gZXhpc3Rpbmcgb25lLlxuICAgKiBAcGFyYW0ge21vZHVsZTpzb3VuZHdvcmtzL2NsaWVudC5QbGF0Zm9ybX5kZWZpbml0aW9ufSBvYmogLSBEZWZpbml0aW9uIG9mXG4gICAqICB0aGUgZmVhdHVyZSB0byBhZGQgdG8gdGhlIGV4aXN0aW5nIG9uZXMuXG4gICAqL1xuICBhZGRGZWF0dXJlRGVmaW5pdGlvbihvYmopIHtcbiAgICB0aGlzLl9mZWF0dXJlRGVmaW5pdGlvbnNbb2JqLmlkXSA9IG9iajtcbiAgfVxuXG4gIC8qKlxuICAgKiBSZXF1aXJlIGZlYXR1cmVzIGF2YWxhYmlsaXR5IGZvciB0aGUgYXBwbGljYXRpb24uXG4gICAqIEBwcml2YXRlXG4gICAqIEBwYXJhbSB7Li4uU3RyaW5nfSBmZWF0dXJlcyAtIFRoZSBpZChzKSBvZiB0aGUgZmVhdHVyZShzKSB0byBiZSByZXF1aXJlZC5cbiAgICovXG4gIHJlcXVpcmVGZWF0dXJlKC4uLmZlYXR1cmVzKSB7XG4gICAgZmVhdHVyZXMuZm9yRWFjaCgoaWQpID0+IHRoaXMuX3JlcXVpcmVkRmVhdHVyZXMuYWRkKGlkKSk7XG4gIH1cblxuICAvKipcbiAgICogRXhlY3V0ZSBhbGwgYGNoZWNrYCBmdW5jdGlvbnMgZnJvbSB0aGUgZGVmaW5pdGlvbiBvZiB0aGUgcmVxdWlyZWQgZmVhdHVyZXMuXG4gICAqIEBwcml2YXRlXG4gICAqIEByZXR1cm4ge0Jvb2xlYW59IC0gdHJ1ZSBpZiBhbGwgY2hlY2tzIHBhc3MsIGZhbHNlIG90aGVyd2lzZS5cbiAgICpcbiAgICovXG4gIHJlc29sdmVSZXF1aXJlZEZlYXR1cmVzKCkge1xuICAgIGxldCByZXN1bHQgPSB0cnVlO1xuXG4gICAgdGhpcy5fcmVxdWlyZWRGZWF0dXJlcy5mb3JFYWNoKChmZWF0dXJlKSA9PiB7XG4gICAgICBjb25zdCBjaGVja0Z1bmN0aW9uID0gdGhpcy5fZmVhdHVyZURlZmluaXRpb25zW2ZlYXR1cmVdLmNoZWNrO1xuXG4gICAgICBpZiAoISh0eXBlb2YgY2hlY2tGdW5jdGlvbiA9PT0gJ2Z1bmN0aW9uJykpXG4gICAgICAgIHRocm93IG5ldyBFcnJvcihgTm8gY2hlY2sgZnVuY3Rpb24gZGVmaW5lZCBmb3IgJHtmZWF0dXJlfSBmZWF0dXJlYCk7XG5cbiAgICAgIHJlc3VsdCA9IHJlc3VsdCAmJiBjaGVja0Z1bmN0aW9uKCk7XG4gICAgfSk7XG5cbiAgICByZXR1cm4gcmVzdWx0O1xuICB9XG5cbiAgLyoqXG4gICAqIFJldHVybnMgdGhlIGxpc3Qgb2YgdGhlIGZ1bmN0aW9ucyB0byBiZSBleGVjdXRlZCBvbiBgc3RhcnRgIGxpZmVjeWNsZS5cbiAgICogQHByaXZhdGVcbiAgICogQHJldHVybiB7QXJyYXl9XG4gICAqL1xuICBnZXRTdGFydEhvb2tzKCkge1xuICAgIHJldHVybiB0aGlzLl9nZXRIb29rcygnc3RhcnRIb29rJyk7XG4gIH1cblxuICAvKipcbiAgICogUmV0dXJucyB0aGUgbGlzdCBvZiB0aGUgZnVuY3Rpb25zIHRvIGJlIGV4ZWN1dGVkIHdoZW4gdGhlIHVzZXJcbiAgICogaW50ZXJhY3RzIHdpdGggdGhlIGFwcGxpY2F0aW9uIGZvciB0aGUgZmlyc3QgdGltZS5cbiAgICogQHByaXZhdGVcbiAgICogQHJldHVybiB7QXJyYXl9XG4gICAqL1xuICBnZXRJbnRlcmFjdGlvbkhvb2tzKCkge1xuICAgIHJldHVybiB0aGlzLl9nZXRIb29rcygnaW50ZXJhY3Rpb25Ib29rJyk7XG4gIH1cblxuICAvKiogQHByaXZhdGUgKi9cbiAgX2dldEhvb2tzKHR5cGUpIHtcbiAgICBjb25zdCBob29rcyA9IFtdO1xuXG4gICAgdGhpcy5fcmVxdWlyZWRGZWF0dXJlcy5mb3JFYWNoKChmZWF0dXJlKSA9PiB7XG4gICAgICBjb25zdCBob29rID0gdGhpcy5fZmVhdHVyZURlZmluaXRpb25zW2ZlYXR1cmVdW3R5cGVdO1xuXG4gICAgICBpZiAoaG9vaylcbiAgICAgICAgaG9va3MucHVzaChob29rKTtcbiAgICB9KTtcblxuICAgIHJldHVybiBob29rcztcbiAgfVxuXG4gIC8qKlxuICAgKiBFeGVjdXRlIGBpbnRlcmFjdGlvbnNgIGhvb2tzIGZyb20gdGhlIGBwbGF0Zm9ybWAgc2VydmljZS5cbiAgICogQWxzbyBhY3RpdmF0ZSB0aGUgbWVkaWEgYWNjb3JkaW5nIHRvIHRoZSBgb3B0aW9uc2AuXG4gICAqIEBwcml2YXRlXG4gICAqL1xuICBfb25JbnRlcmFjdGlvbigpIHtcbiAgICAvLyBleGVjdXRlIGludGVyYWN0aW9uIGhvb2tzIGZyb20gdGhlIHBsYXRmb3JtXG4gICAgY29uc3QgaW50ZXJhY3Rpb25Ib29rcyA9IHRoaXMuZ2V0SW50ZXJhY3Rpb25Ib29rcygpO1xuICAgIGludGVyYWN0aW9uSG9va3MuZm9yRWFjaCgoaG9vaykgPT4gaG9vaygpKTtcblxuICAgIC8vIEB0b2RvIC0gZml4IGFuZCB0cmFuc2Zvcm0gaW50byBhIGZlYXR1cmVcbiAgICAvLyBpZiAodGhpcy5vcHRpb25zLndha2VMb2NrKVxuICAgIC8vICAgdGhpcy5faW5pdFdha2VMb2NrKCk7XG5cbiAgICB0aGlzLnJlYWR5KCk7XG4gIH1cblxuICAvKipcbiAgICogUG9wdWxhdGUgYGNsaWVudC5wbGF0Zm9ybWAgd2l0aCB0aGUgcHJlZmVyZWQgYXVkaW8gZmlsZSBleHRlbnRpb24gZm9yIHRoZSBwbGF0Zm9ybS5cbiAgICogQHByaXZhdGVcbiAgICovXG4gIF9kZWZpbmVBdWRpb0ZpbGVFeHRlbnRpb24oKSB7XG4gICAgY29uc3QgYSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2F1ZGlvJyk7XG4gICAgLy8gaHR0cDovL2RpdmVpbnRvaHRtbDUuaW5mby9ldmVyeXRoaW5nLmh0bWxcbiAgICBpZiAoISEoYS5jYW5QbGF5VHlwZSAmJiBhLmNhblBsYXlUeXBlKCdhdWRpby9tcGVnOycpKSkge1xuICAgICAgY2xpZW50LnBsYXRmb3JtLmF1ZGlvRmlsZUV4dCA9ICcubXAzJztcbiAgICB9IGVsc2UgaWYgKCEhKGEuY2FuUGxheVR5cGUgJiYgYS5jYW5QbGF5VHlwZSgnYXVkaW8vb2dnOyBjb2RlY3M9XCJ2b3JiaXNcIicpKSkge1xuICAgICAgY2xpZW50LnBsYXRmb3JtLmF1ZGlvRmlsZUV4dCA9ICcub2dnJztcbiAgICB9IGVsc2Uge1xuICAgICAgY2xpZW50LnBsYXRmb3JtLmF1ZGlvRmlsZUV4dCA9ICcud2F2JztcbiAgICB9XG4gIH1cblxuICAvKipcbiAgICogUG9wdWxhdGUgYGNsaWVudC5wbGF0Zm9ybWAgd2l0aCB0aGUgb3MgbmFtZS5cbiAgICogQHByaXZhdGVcbiAgICovXG4gIF9kZWZpbmVQbGF0Zm9ybSgpIHtcbiAgICBjb25zdCB1YSA9IHdpbmRvdy5uYXZpZ2F0b3IudXNlckFnZW50XG4gICAgY29uc3QgbWQgPSBuZXcgTW9iaWxlRGV0ZWN0KHVhKTtcblxuICAgIGNsaWVudC5wbGF0Zm9ybS5pc01vYmlsZSA9IChtZC5tb2JpbGUoKSAhPT0gbnVsbCk7IC8vIHRydWUgaWYgcGhvbmUgb3IgdGFibGV0XG4gICAgY2xpZW50LnBsYXRmb3JtLm9zID0gKGZ1bmN0aW9uKCkge1xuICAgICAgY29uc3Qgb3MgPSBtZC5vcygpO1xuXG4gICAgICBpZiAob3MgPT09ICdBbmRyb2lkT1MnKVxuICAgICAgICByZXR1cm4gJ2FuZHJvaWQnO1xuICAgICAgZWxzZSBpZiAob3MgPT09ICdpT1MnKVxuICAgICAgICByZXR1cm4gJ2lvcyc7XG4gICAgICBlbHNlXG4gICAgICAgIHJldHVybiAnb3RoZXInO1xuICAgIH0pKCk7XG4gIH1cblxuICAvLyBAdG9kbyAtIGZpeCB0cmFuc2Zvcm0gaW50byBmZWF0dXJlIGRlZmluaXRpb25cbiAgLy8gaGFja3MgdG8ga2VlcCB0aGUgZGV2aWNlIGF3YWtlLi4uXG4gIC8vIGNmLiBodHRwczovL2dpdGh1Yi5jb20vYm9yaXNtdXMvd2VidnItYm9pbGVycGxhdGUvYmxvYi84YWJiYzc0Y2ZhNTk3NmI5YWIwYzM4OGNiMGM1MTk0NDAwOGM2OTg5L2pzL3dlYnZyLW1hbmFnZXIuanMjTDI2OC1MMjg5XG4gIF9pbml0V2FrZUxvY2soKSB7XG4gICAgdGhpcy5fd2FrZUxvY2tWaWRlbyA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ3ZpZGVvJyk7XG5cbiAgICB0aGlzLl93YWtlTG9ja1ZpZGVvLmFkZEV2ZW50TGlzdGVuZXIoJ2VuZGVkJywgKCkgPT4ge1xuICAgICAgdGhpcy5fd2FrZUxvY2tWaWRlby5wbGF5KCk7XG4gICAgfSk7XG4gIH1cblxuICBfcmVxdWVzdFdha2VMb2NrKCkge1xuICAgIGNvbnN0IG9zID0gY2xpZW50LnBsYXRmb3JtLm9zO1xuICAgIHRoaXMuX3JlbGVhc2VXYWtlQ2xvY2soKTtcblxuICAgIGlmIChvcyA9PT0gJ2lvcycpIHtcbiAgICAgIGlmICh0aGlzLl93YWtlTG9ja1RpbWVyKSByZXR1cm47XG5cbiAgICAgIHRoaXMuX3dha2VMb2NrVGltZXIgPSBzZXRJbnRlcnZhbCgoKSA9PiB7XG4gICAgICAgIHdpbmRvdy5sb2NhdGlvbiA9IHdpbmRvdy5sb2NhdGlvbjtcbiAgICAgICAgc2V0VGltZW91dCh3aW5kb3cuc3RvcCwgMCk7XG4gICAgICB9LCAzMDAwMCk7XG4gICAgfSBlbHNlIGlmIChvcyA9PT0gJ2FuZHJvaWQnKSB7XG4gICAgICBpZiAodGhpcy5fd2FrZUxvY2tWaWRlby5wYXVzZWQgPT09IGZhbHNlKSByZXR1cm47XG5cbiAgICAgIHRoaXMuX3dha2VMb2NrVmlkZW8uc3JjID0gX2Jhc2U2NCgndmlkZW8vd2VibScsICdHa1hmb3dFQUFBQUFBQUFmUW9hQkFVTDNnUUZDOG9FRVF2T0JDRUtDaEhkbFltMUNoNEVDUW9XQkFoaFRnR2NCQUFBQUFBQUNXeEZObTNSQUxFMjdpMU9yaEJWSnFXWlRySUhmVGJ1TVU2dUVGbFN1YTFPc2dnRXVUYnVNVTZ1RUhGTzdhMU9zZ2dJKzdBRUFBQUFBQUFDa0FBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQVZTYWxtQVFBQUFBQUFBRU1xMTdHREQwSkFUWUNNVEdGMlpqVTJMalF1TVRBeFYwR01UR0YyWmpVMkxqUXVNVEF4YzZTUTIwWXYvRWx3czczQS8rS2ZFak0xMUVTSmlFQmt3QUFBQUFBQUZsU3Vhd0VBQUFBQUFBQkhyZ0VBQUFBQUFBQSsxNEVCYzhXQkFaeUJBQ0sxbklOMWJtU0doVlpmVmxBNGc0RUJJK09EaEFUM2tOWGdBUUFBQUFBQUFCS3dnUkM2Z1JCVHdJRUJWTENCRUZTNmdSQWZRN1oxQVFBQUFBQUFBTEhuZ1FDZ0FRQUFBQUFBQUZ5aG80RUFBSUFRQWdDZEFTb1FBQkFBQUVjSWhZV0loWVNJQWdJQURBMWdBUDcvcTFDQWRhRUJBQUFBQUFBQUxhWUJBQUFBQUFBQUpPNkJBYVdmRUFJQW5RRXFFQUFRQUFCSENJV0ZpSVdFaUFJQ0FBd05ZQUQrLzdyL1FLQUJBQUFBQUFBQVFLR1ZnUUJUQUxFQkFBRVFFQUFZQUJoWUwvUUFDQUFBZGFFQkFBQUFBQUFBSDZZQkFBQUFBQUFBRnU2QkFhV1JzUUVBQVJBUUFCZ0FHRmd2OUFBSUFBQWNVN3RyQVFBQUFBQUFBQkc3ajdPQkFMZUs5NEVCOFlJQmdmQ0JBdz09Jyk7XG4gICAgICB0aGlzLl93YWtlTG9ja1ZpZGVvLnBsYXkoKTtcbiAgICB9XG4gIH1cblxuICBfcmVsZWFzZVdha2VDbG9jaygpIHtcbiAgICBjb25zdCBvcyA9IGNsaWVudC5wbGF0Zm9ybS5vcztcblxuICAgIGlmIChvcyA9PT0gJ2lvcycpIHtcbiAgICAgIGlmICh0aGlzLl93YWtlTG9ja1RpbWVyKSB7XG4gICAgICAgIGNsZWFySW50ZXJ2YWwodGhpcy5fd2FrZUxvY2tUaW1lcik7XG4gICAgICAgIHRoaXMuX3dha2VMb2NrVGltZXIgPSBudWxsO1xuICAgICAgfVxuICAgIH0gZWxzZSBpZiAob3MgPT09ICdhbmRyb2lkJykge1xuICAgICAgdGhpcy5fd2FrZUxvY2tWaWRlby5wYXVzZSgpO1xuICAgICAgdGhpcy5fd2FrZUxvY2tWaWRlby5zcmMgPSAnJztcbiAgICB9XG4gIH1cbn1cblxuc2VydmljZU1hbmFnZXIucmVnaXN0ZXIoU0VSVklDRV9JRCwgUGxhdGZvcm0pO1xuXG5leHBvcnQgZGVmYXVsdCBQbGF0Zm9ybTtcbiJdfQ==