'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _toConsumableArray2 = require('babel-runtime/helpers/toConsumableArray');

var _toConsumableArray3 = _interopRequireDefault(_toConsumableArray2);

var _set = require('babel-runtime/core-js/set');

var _set2 = _interopRequireDefault(_set);

var _getPrototypeOf = require('babel-runtime/core-js/object/get-prototype-of');

var _getPrototypeOf2 = _interopRequireDefault(_getPrototypeOf);

var _classCallCheck2 = require('babel-runtime/helpers/classCallCheck');

var _classCallCheck3 = _interopRequireDefault(_classCallCheck2);

var _createClass2 = require('babel-runtime/helpers/createClass');

var _createClass3 = _interopRequireDefault(_createClass2);

var _possibleConstructorReturn2 = require('babel-runtime/helpers/possibleConstructorReturn');

var _possibleConstructorReturn3 = _interopRequireDefault(_possibleConstructorReturn2);

var _get2 = require('babel-runtime/helpers/get');

var _get3 = _interopRequireDefault(_get2);

var _inherits2 = require('babel-runtime/helpers/inherits');

var _inherits3 = _interopRequireDefault(_inherits2);

var _wavesAudio = require('waves-audio');

var _client = require('../core/client');

var _client2 = _interopRequireDefault(_client);

var _mobileDetect = require('mobile-detect');

var _mobileDetect2 = _interopRequireDefault(_mobileDetect);

var _SegmentedView = require('../views/SegmentedView');

var _SegmentedView2 = _interopRequireDefault(_SegmentedView);

var _Service2 = require('../core/Service');

var _Service3 = _interopRequireDefault(_Service2);

var _serviceManager = require('../core/serviceManager');

var _serviceManager2 = _interopRequireDefault(_serviceManager);

var _webrtcAdapter = require('webrtc-adapter');

var adapter = _interopRequireWildcard(_webrtcAdapter);

function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } else { var newObj = {}; if (obj != null) { for (var key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) newObj[key] = obj[key]; } } newObj.default = obj; return newObj; } }

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

adapter.disableLog(true);

// to be added
// + “video-input”: needs video input
// + “video-audio-input”: needs video input
// + DeviceMotion/Orientation conditions generated by the motion-input module

// @todo - define if we keep this
var defaultDefinitions = [{
  id: 'web-audio',
  check: function check() {
    return !!_wavesAudio.audioContext;
  },
  interactionHook: function interactionHook() {
    if (!_client2.default.platform.isMobile) return;

    var g = _wavesAudio.audioContext.createGain();
    g.connect(_wavesAudio.audioContext.destination);
    g.gain.value = 0.000000001; // -180dB ?

    var o = _wavesAudio.audioContext.createOscillator();
    o.connect(g);
    o.frequency.value = 20;
    o.start(0);

    // prevent android to stop audio by keping the oscillator active
    if (_client2.default.platform.os !== 'android') o.stop(_wavesAudio.audioContext.currentTime + 0.01);
  }
}, {
  // @note: `touch` feature workaround
  // cf. http://www.stucox.com/blog/you-cant-detect-a-touchscreen/
  id: 'mobile-device',
  check: function check() {
    return _client2.default.platform.isMobile;
  }
}, {
  id: 'audio-input',
  check: function check() {
    return !!navigator.getUserMedia;
  },
  startHook: function startHook() {
    navigator.getUserMedia({ audio: true }, function (stream) {
      stream.getAudioTracks()[0].stop();
    }, function (err) {
      throw err;
    });
  }
}];

var SERVICE_ID = 'service:platform';

var Platform = function (_Service) {
  (0, _inherits3.default)(Platform, _Service);

  function Platform() {
    (0, _classCallCheck3.default)(this, Platform);

    var _this = (0, _possibleConstructorReturn3.default)(this, (0, _getPrototypeOf2.default)(Platform).call(this, SERVICE_ID, false));

    var defaults = {
      viewCtor: _SegmentedView2.default,
      viewPriority: 20
    };

    _this.configure(defaults);

    _this._requiredFeatures = new _set2.default();
    _this._featureDefinitions = {};

    defaultDefinitions.forEach(function (def) {
      return _this.addFeatureDefinition(def);
    });
    return _this;
  }

  /** @inheritdoc */


  (0, _createClass3.default)(Platform, [{
    key: 'configure',
    value: function configure(options) {
      if (options.features) {
        var features = options.features;

        if (typeof features === 'string') features = [features];

        this.requireFeature.apply(this, (0, _toConsumableArray3.default)(features));
        delete options.features;
      }

      (0, _get3.default)((0, _getPrototypeOf2.default)(Platform.prototype), 'configure', this).call(this, options);
    }

    /** @inheritdoc */

  }, {
    key: 'init',
    value: function init() {
      this._defineAudioFileExtention();
      this._definePlatform();
      // resolve required features from the application
      _client2.default.compatible = this.resolveRequiredFeatures();

      this.viewCtor = this.options.viewCtor;
      this.view = this.createView();
    }

    /** @inheritdoc */

  }, {
    key: 'start',
    value: function start() {
      (0, _get3.default)((0, _getPrototypeOf2.default)(Platform.prototype), 'start', this).call(this);

      if (!this.hasStarted) this.init();

      if (_client2.default.compatible) this.ready();else this.show();
    }

    /**
     * Add a new feature definition or override an existing one.
     * @param {Object} obj - The definition of the feature.
     * @param {String} obj.id - The id of the definition.
     * @param {Function} obj.check - A function returning true if the feature is
     *  available or false otherwise.
     * @param {Function} [obj.startHook=undefined] - A function to be executed by the
     *  `welcome` service when starting.
     * @param {Function} [obj.interactionHook=undefined] - A function to be executed by the
     *  `welcome` service when the user interact with the device (i.e. on `click` or
     *  `touchstart`).
     */

  }, {
    key: 'addFeatureDefinition',
    value: function addFeatureDefinition(obj) {
      this._featureDefinitions[obj.id] = obj;
    }

    /**
     * Add feature(s) to the ones required by the application.
     * @param {...String} features - The id(s) of the feature(s) to be required.
     */

  }, {
    key: 'requireFeature',
    value: function requireFeature() {
      var _this2 = this;

      for (var _len = arguments.length, features = Array(_len), _key = 0; _key < _len; _key++) {
        features[_key] = arguments[_key];
      }

      features.forEach(function (id) {
        return _this2._requiredFeatures.add(id);
      });
    }

    /**
     * Execute all `check` functions according to the required features
     * @return {Boolean} - true if all checks pass, false otherwise.
     */

  }, {
    key: 'resolveRequiredFeatures',
    value: function resolveRequiredFeatures() {
      var _this3 = this;

      var result = true;

      this._requiredFeatures.forEach(function (feature) {
        var checkFunction = _this3._featureDefinitions[feature].check;

        if (!(typeof checkFunction === 'function')) throw new Error('No check function defined for ' + feature + ' feature');

        result = result && checkFunction();
      });

      return result;
    }

    /**
     * Returns the list of the functions to be executed on welcome `start` lifecycle.
     * @return {Array}
     */

  }, {
    key: 'getStartHooks',
    value: function getStartHooks() {
      return this._getHooks('startHook');
    }

    /**
     * Returns the list of the functions to be executed on welcome when the user
     * interacts with the application.
     * @return {Array}
     */

  }, {
    key: 'getInteractionHooks',
    value: function getInteractionHooks() {
      return this._getHooks('interactionHook');
    }

    /** @private */

  }, {
    key: '_getHooks',
    value: function _getHooks(type) {
      var _this4 = this;

      var hooks = [];

      this._requiredFeatures.forEach(function (feature) {
        var hook = _this4._featureDefinitions[feature][type];

        if (hook) hooks.push(hook);
      });

      return hooks;
    }

    /**
     * Populate `client.platform` with the prefered audio file extention
     * for the platform.
     */

  }, {
    key: '_defineAudioFileExtention',
    value: function _defineAudioFileExtention() {
      var a = document.createElement('audio');
      // http://diveintohtml5.info/everything.html
      if (!!(a.canPlayType && a.canPlayType('audio/mpeg;'))) {
        _client2.default.platform.audioFileExt = '.mp3';
      } else if (!!(a.canPlayType && a.canPlayType('audio/ogg; codecs="vorbis"'))) {
        _client2.default.platform.audioFileExt = '.ogg';
      } else {
        _client2.default.platform.audioFileExt = '.wav';
      }
    }

    /**
     * Populate `client.platform` with the os name.
     */

  }, {
    key: '_definePlatform',
    value: function _definePlatform() {
      var ua = window.navigator.userAgent;
      var md = new _mobileDetect2.default(ua);

      _client2.default.platform.isMobile = md.mobile() !== null; // true if phone or tablet
      _client2.default.platform.os = function () {
        var os = md.os();

        if (os === 'AndroidOS') return 'android';else if (os === 'iOS') return 'ios';else return 'other';
      }();
    }
  }]);
  return Platform;
}(_Service3.default);

_serviceManager2.default.register(SERVICE_ID, Platform);

exports.default = Platform;
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIlBsYXRmb3JtLmpzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0FBQUE7O0FBQ0E7Ozs7QUFDQTs7OztBQUNBOzs7O0FBQ0E7Ozs7QUFDQTs7OztBQUdBOztJQUFZOzs7Ozs7QUFDWixRQUFRLFVBQVIsQ0FBbUIsSUFBbkI7Ozs7Ozs7O0FBT0EsSUFBTSxxQkFBcUIsQ0FDekI7QUFDRSxNQUFJLFdBQUo7QUFDQSxTQUFPLGlCQUFXO0FBQ2hCLFdBQU8sQ0FBQyx5QkFBRCxDQURTO0dBQVg7QUFHUCxtQkFBaUIsMkJBQVc7QUFDMUIsUUFBSSxDQUFDLGlCQUFPLFFBQVAsQ0FBZ0IsUUFBaEIsRUFDSCxPQURGOztBQUdBLFFBQU0sSUFBSSx5QkFBYSxVQUFiLEVBQUosQ0FKb0I7QUFLMUIsTUFBRSxPQUFGLENBQVUseUJBQWEsV0FBYixDQUFWLENBTDBCO0FBTTFCLE1BQUUsSUFBRixDQUFPLEtBQVAsR0FBZSxXQUFmOztBQU4wQixRQVFwQixJQUFJLHlCQUFhLGdCQUFiLEVBQUosQ0FSb0I7QUFTMUIsTUFBRSxPQUFGLENBQVUsQ0FBVixFQVQwQjtBQVUxQixNQUFFLFNBQUYsQ0FBWSxLQUFaLEdBQW9CLEVBQXBCLENBVjBCO0FBVzFCLE1BQUUsS0FBRixDQUFRLENBQVI7OztBQVgwQixRQWN0QixpQkFBTyxRQUFQLENBQWdCLEVBQWhCLEtBQXVCLFNBQXZCLEVBQ0YsRUFBRSxJQUFGLENBQU8seUJBQWEsV0FBYixHQUEyQixJQUEzQixDQUFQLENBREY7R0FkZTtDQU5NLEVBd0J6Qjs7O0FBR0UsTUFBSSxlQUFKO0FBQ0EsU0FBTyxpQkFBVztBQUNoQixXQUFPLGlCQUFPLFFBQVAsQ0FBZ0IsUUFBaEIsQ0FEUztHQUFYO0NBNUJnQixFQWdDekI7QUFDRSxNQUFJLGFBQUo7QUFDQSxTQUFPLGlCQUFXO0FBQ2hCLFdBQU8sQ0FBQyxDQUFDLFVBQVUsWUFBVixDQURPO0dBQVg7QUFHUCxhQUFXLHFCQUFXO0FBQ3BCLGNBQVUsWUFBVixDQUF1QixFQUFFLE9BQU8sSUFBUCxFQUF6QixFQUF3QyxVQUFTLE1BQVQsRUFBaUI7QUFDdkQsYUFBTyxjQUFQLEdBQXdCLENBQXhCLEVBQTJCLElBQTNCLEdBRHVEO0tBQWpCLEVBRXJDLFVBQVUsR0FBVixFQUFlO0FBQ2hCLFlBQU0sR0FBTixDQURnQjtLQUFmLENBRkgsQ0FEb0I7R0FBWDtDQXJDWSxDQUFyQjs7QUFnRE4sSUFBTSxhQUFhLGtCQUFiOztJQUVBOzs7QUFDSixXQURJLFFBQ0osR0FBYzt3Q0FEVixVQUNVOzs2RkFEVixxQkFFSSxZQUFZLFFBRE47O0FBR1osUUFBTSxXQUFXO0FBQ2YsdUNBRGU7QUFFZixvQkFBYyxFQUFkO0tBRkksQ0FITTs7QUFRWixVQUFLLFNBQUwsQ0FBZSxRQUFmLEVBUlk7O0FBVVosVUFBSyxpQkFBTCxHQUF5QixtQkFBekIsQ0FWWTtBQVdaLFVBQUssbUJBQUwsR0FBMkIsRUFBM0IsQ0FYWTs7QUFhWix1QkFBbUIsT0FBbkIsQ0FBMkIsVUFBQyxHQUFEO2FBQVMsTUFBSyxvQkFBTCxDQUEwQixHQUExQjtLQUFULENBQTNCLENBYlk7O0dBQWQ7Ozs7OzZCQURJOzs4QkFrQk0sU0FBUztBQUNqQixVQUFJLFFBQVEsUUFBUixFQUFrQjtBQUNwQixZQUFJLFdBQVcsUUFBUSxRQUFSLENBREs7O0FBR3BCLFlBQUksT0FBTyxRQUFQLEtBQW9CLFFBQXBCLEVBQ0YsV0FBVyxDQUFDLFFBQUQsQ0FBWCxDQURGOztBQUdBLGFBQUssY0FBTCw4Q0FBdUIsU0FBdkIsRUFOb0I7QUFPcEIsZUFBTyxRQUFRLFFBQVIsQ0FQYTtPQUF0Qjs7QUFVQSx1REE3QkUsbURBNkJjLFFBQWhCLENBWGlCOzs7Ozs7OzJCQWVaO0FBQ0wsV0FBSyx5QkFBTCxHQURLO0FBRUwsV0FBSyxlQUFMOztBQUZLLHNCQUlMLENBQU8sVUFBUCxHQUFvQixLQUFLLHVCQUFMLEVBQXBCLENBSks7O0FBTUwsV0FBSyxRQUFMLEdBQWdCLEtBQUssT0FBTCxDQUFhLFFBQWIsQ0FOWDtBQU9MLFdBQUssSUFBTCxHQUFZLEtBQUssVUFBTCxFQUFaLENBUEs7Ozs7Ozs7NEJBV0M7QUFDTix1REE3Q0UsOENBNkNGLENBRE07O0FBR04sVUFBSSxDQUFDLEtBQUssVUFBTCxFQUNILEtBQUssSUFBTCxHQURGOztBQUdBLFVBQUksaUJBQU8sVUFBUCxFQUNGLEtBQUssS0FBTCxHQURGLEtBR0UsS0FBSyxJQUFMLEdBSEY7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt5Q0FrQm1CLEtBQUs7QUFDeEIsV0FBSyxtQkFBTCxDQUF5QixJQUFJLEVBQUosQ0FBekIsR0FBbUMsR0FBbkMsQ0FEd0I7Ozs7Ozs7Ozs7cUNBUUU7Ozt3Q0FBVjs7T0FBVTs7QUFDMUIsZUFBUyxPQUFULENBQWlCLFVBQUMsRUFBRDtlQUFRLE9BQUssaUJBQUwsQ0FBdUIsR0FBdkIsQ0FBMkIsRUFBM0I7T0FBUixDQUFqQixDQUQwQjs7Ozs7Ozs7Ozs4Q0FRRjs7O0FBQ3hCLFVBQUksU0FBUyxJQUFULENBRG9COztBQUd4QixXQUFLLGlCQUFMLENBQXVCLE9BQXZCLENBQStCLFVBQUMsT0FBRCxFQUFhO0FBQzFDLFlBQU0sZ0JBQWdCLE9BQUssbUJBQUwsQ0FBeUIsT0FBekIsRUFBa0MsS0FBbEMsQ0FEb0I7O0FBRzFDLFlBQUksRUFBRSxPQUFPLGFBQVAsS0FBeUIsVUFBekIsQ0FBRixFQUNGLE1BQU0sSUFBSSxLQUFKLG9DQUEyQyxvQkFBM0MsQ0FBTixDQURGOztBQUdBLGlCQUFTLFVBQVUsZUFBVixDQU5pQztPQUFiLENBQS9CLENBSHdCOztBQVl4QixhQUFPLE1BQVAsQ0Fad0I7Ozs7Ozs7Ozs7b0NBbUJWO0FBQ2QsYUFBTyxLQUFLLFNBQUwsQ0FBZSxXQUFmLENBQVAsQ0FEYzs7Ozs7Ozs7Ozs7MENBU007QUFDcEIsYUFBTyxLQUFLLFNBQUwsQ0FBZSxpQkFBZixDQUFQLENBRG9COzs7Ozs7OzhCQUtaLE1BQU07OztBQUNkLFVBQU0sUUFBUSxFQUFSLENBRFE7O0FBR2QsV0FBSyxpQkFBTCxDQUF1QixPQUF2QixDQUErQixVQUFDLE9BQUQsRUFBYTtBQUMxQyxZQUFNLE9BQU8sT0FBSyxtQkFBTCxDQUF5QixPQUF6QixFQUFrQyxJQUFsQyxDQUFQLENBRG9DOztBQUcxQyxZQUFJLElBQUosRUFDRSxNQUFNLElBQU4sQ0FBVyxJQUFYLEVBREY7T0FINkIsQ0FBL0IsQ0FIYzs7QUFVZCxhQUFPLEtBQVAsQ0FWYzs7Ozs7Ozs7OztnREFpQlk7QUFDMUIsVUFBTSxJQUFJLFNBQVMsYUFBVCxDQUF1QixPQUF2QixDQUFKOztBQURvQixVQUd0QixDQUFDLEVBQUUsRUFBRSxXQUFGLElBQWlCLEVBQUUsV0FBRixDQUFjLGFBQWQsQ0FBakIsQ0FBRixFQUFrRDtBQUNyRCx5QkFBTyxRQUFQLENBQWdCLFlBQWhCLEdBQStCLE1BQS9CLENBRHFEO09BQXZELE1BRU8sSUFBSSxDQUFDLEVBQUUsRUFBRSxXQUFGLElBQWlCLEVBQUUsV0FBRixDQUFjLDRCQUFkLENBQWpCLENBQUYsRUFBaUU7QUFDM0UseUJBQU8sUUFBUCxDQUFnQixZQUFoQixHQUErQixNQUEvQixDQUQyRTtPQUF0RSxNQUVBO0FBQ0wseUJBQU8sUUFBUCxDQUFnQixZQUFoQixHQUErQixNQUEvQixDQURLO09BRkE7Ozs7Ozs7OztzQ0FVUztBQUNoQixVQUFNLEtBQUssT0FBTyxTQUFQLENBQWlCLFNBQWpCLENBREs7QUFFaEIsVUFBTSxLQUFLLDJCQUFpQixFQUFqQixDQUFMLENBRlU7O0FBSWhCLHVCQUFPLFFBQVAsQ0FBZ0IsUUFBaEIsR0FBNEIsR0FBRyxNQUFILE9BQWdCLElBQWhCO0FBSlosc0JBS2hCLENBQU8sUUFBUCxDQUFnQixFQUFoQixHQUFxQixZQUFZO0FBQy9CLFlBQU0sS0FBSyxHQUFHLEVBQUgsRUFBTCxDQUR5Qjs7QUFHL0IsWUFBSSxPQUFPLFdBQVAsRUFDRixPQUFPLFNBQVAsQ0FERixLQUVLLElBQUksT0FBTyxLQUFQLEVBQ1AsT0FBTyxLQUFQLENBREcsS0FHSCxPQUFPLE9BQVAsQ0FIRztPQUxlLEVBQXRCLENBTGdCOzs7U0FySmQ7OztBQXVLTix5QkFBZSxRQUFmLENBQXdCLFVBQXhCLEVBQW9DLFFBQXBDOztrQkFFZSIsImZpbGUiOiJQbGF0Zm9ybS5qcyIsInNvdXJjZXNDb250ZW50IjpbImltcG9ydCB7IGF1ZGlvQ29udGV4dCB9IGZyb20gJ3dhdmVzLWF1ZGlvJztcbmltcG9ydCBjbGllbnQgZnJvbSAnLi4vY29yZS9jbGllbnQnO1xuaW1wb3J0IE1vYmlsZURldGVjdCBmcm9tICdtb2JpbGUtZGV0ZWN0JztcbmltcG9ydCBTZWdtZW50ZWRWaWV3IGZyb20gJy4uL3ZpZXdzL1NlZ21lbnRlZFZpZXcnO1xuaW1wb3J0IFNlcnZpY2UgZnJvbSAnLi4vY29yZS9TZXJ2aWNlJztcbmltcG9ydCBzZXJ2aWNlTWFuYWdlciBmcm9tICcuLi9jb3JlL3NlcnZpY2VNYW5hZ2VyJztcblxuLy8gQHRvZG8gLSBkZWZpbmUgaWYgd2Uga2VlcCB0aGlzXG5pbXBvcnQgKiBhcyBhZGFwdGVyIGZyb20gJ3dlYnJ0Yy1hZGFwdGVyJztcbmFkYXB0ZXIuZGlzYWJsZUxvZyh0cnVlKTtcblxuLy8gdG8gYmUgYWRkZWRcbi8vICsg4oCcdmlkZW8taW5wdXTigJ06IG5lZWRzIHZpZGVvIGlucHV0XG4vLyArIOKAnHZpZGVvLWF1ZGlvLWlucHV04oCdOiBuZWVkcyB2aWRlbyBpbnB1dFxuLy8gKyBEZXZpY2VNb3Rpb24vT3JpZW50YXRpb24gY29uZGl0aW9ucyBnZW5lcmF0ZWQgYnkgdGhlIG1vdGlvbi1pbnB1dCBtb2R1bGVcblxuY29uc3QgZGVmYXVsdERlZmluaXRpb25zID0gW1xuICB7XG4gICAgaWQ6ICd3ZWItYXVkaW8nLFxuICAgIGNoZWNrOiBmdW5jdGlvbigpIHtcbiAgICAgIHJldHVybiAhIWF1ZGlvQ29udGV4dDtcbiAgICB9LFxuICAgIGludGVyYWN0aW9uSG9vazogZnVuY3Rpb24oKSB7XG4gICAgICBpZiAoIWNsaWVudC5wbGF0Zm9ybS5pc01vYmlsZSlcbiAgICAgICAgcmV0dXJuO1xuXG4gICAgICBjb25zdCBnID0gYXVkaW9Db250ZXh0LmNyZWF0ZUdhaW4oKTtcbiAgICAgIGcuY29ubmVjdChhdWRpb0NvbnRleHQuZGVzdGluYXRpb24pO1xuICAgICAgZy5nYWluLnZhbHVlID0gMC4wMDAwMDAwMDE7IC8vIC0xODBkQiA/XG5cbiAgICAgIGNvbnN0IG8gPSBhdWRpb0NvbnRleHQuY3JlYXRlT3NjaWxsYXRvcigpO1xuICAgICAgby5jb25uZWN0KGcpO1xuICAgICAgby5mcmVxdWVuY3kudmFsdWUgPSAyMDtcbiAgICAgIG8uc3RhcnQoMCk7XG5cbiAgICAgIC8vIHByZXZlbnQgYW5kcm9pZCB0byBzdG9wIGF1ZGlvIGJ5IGtlcGluZyB0aGUgb3NjaWxsYXRvciBhY3RpdmVcbiAgICAgIGlmIChjbGllbnQucGxhdGZvcm0ub3MgIT09ICdhbmRyb2lkJylcbiAgICAgICAgby5zdG9wKGF1ZGlvQ29udGV4dC5jdXJyZW50VGltZSArIDAuMDEpO1xuICAgIH1cbiAgfSxcbiAge1xuICAgIC8vIEBub3RlOiBgdG91Y2hgIGZlYXR1cmUgd29ya2Fyb3VuZFxuICAgIC8vIGNmLiBodHRwOi8vd3d3LnN0dWNveC5jb20vYmxvZy95b3UtY2FudC1kZXRlY3QtYS10b3VjaHNjcmVlbi9cbiAgICBpZDogJ21vYmlsZS1kZXZpY2UnLFxuICAgIGNoZWNrOiBmdW5jdGlvbigpIHtcbiAgICAgIHJldHVybiBjbGllbnQucGxhdGZvcm0uaXNNb2JpbGU7XG4gICAgfVxuICB9LFxuICB7XG4gICAgaWQ6ICdhdWRpby1pbnB1dCcsXG4gICAgY2hlY2s6IGZ1bmN0aW9uKCkge1xuICAgICAgcmV0dXJuICEhbmF2aWdhdG9yLmdldFVzZXJNZWRpYTtcbiAgICB9LFxuICAgIHN0YXJ0SG9vazogZnVuY3Rpb24oKSB7XG4gICAgICBuYXZpZ2F0b3IuZ2V0VXNlck1lZGlhKHsgYXVkaW86IHRydWUgfSwgZnVuY3Rpb24oc3RyZWFtKSB7XG4gICAgICAgIHN0cmVhbS5nZXRBdWRpb1RyYWNrcygpWzBdLnN0b3AoKTtcbiAgICAgIH0sIGZ1bmN0aW9uIChlcnIpIHtcbiAgICAgICAgdGhyb3cgZXJyO1xuICAgICAgfSk7XG4gICAgfVxuICB9XG5dO1xuXG5cbmNvbnN0IFNFUlZJQ0VfSUQgPSAnc2VydmljZTpwbGF0Zm9ybSc7XG5cbmNsYXNzIFBsYXRmb3JtIGV4dGVuZHMgU2VydmljZSB7XG4gIGNvbnN0cnVjdG9yKCkge1xuICAgIHN1cGVyKFNFUlZJQ0VfSUQsIGZhbHNlKTtcblxuICAgIGNvbnN0IGRlZmF1bHRzID0ge1xuICAgICAgdmlld0N0b3I6IFNlZ21lbnRlZFZpZXcsXG4gICAgICB2aWV3UHJpb3JpdHk6IDIwLFxuICAgIH07XG5cbiAgICB0aGlzLmNvbmZpZ3VyZShkZWZhdWx0cyk7XG5cbiAgICB0aGlzLl9yZXF1aXJlZEZlYXR1cmVzID0gbmV3IFNldCgpO1xuICAgIHRoaXMuX2ZlYXR1cmVEZWZpbml0aW9ucyA9IHt9O1xuXG4gICAgZGVmYXVsdERlZmluaXRpb25zLmZvckVhY2goKGRlZikgPT4gdGhpcy5hZGRGZWF0dXJlRGVmaW5pdGlvbihkZWYpKTtcbiAgfVxuXG4gIC8qKiBAaW5oZXJpdGRvYyAqL1xuICBjb25maWd1cmUob3B0aW9ucykge1xuICAgIGlmIChvcHRpb25zLmZlYXR1cmVzKSB7XG4gICAgICBsZXQgZmVhdHVyZXMgPSBvcHRpb25zLmZlYXR1cmVzO1xuXG4gICAgICBpZiAodHlwZW9mIGZlYXR1cmVzID09PSAnc3RyaW5nJylcbiAgICAgICAgZmVhdHVyZXMgPSBbZmVhdHVyZXNdO1xuXG4gICAgICB0aGlzLnJlcXVpcmVGZWF0dXJlKC4uLmZlYXR1cmVzKTtcbiAgICAgIGRlbGV0ZSBvcHRpb25zLmZlYXR1cmVzO1xuICAgIH1cblxuICAgIHN1cGVyLmNvbmZpZ3VyZShvcHRpb25zKTtcbiAgfVxuXG4gIC8qKiBAaW5oZXJpdGRvYyAqL1xuICBpbml0KCkge1xuICAgIHRoaXMuX2RlZmluZUF1ZGlvRmlsZUV4dGVudGlvbigpO1xuICAgIHRoaXMuX2RlZmluZVBsYXRmb3JtKCk7XG4gICAgLy8gcmVzb2x2ZSByZXF1aXJlZCBmZWF0dXJlcyBmcm9tIHRoZSBhcHBsaWNhdGlvblxuICAgIGNsaWVudC5jb21wYXRpYmxlID0gdGhpcy5yZXNvbHZlUmVxdWlyZWRGZWF0dXJlcygpO1xuXG4gICAgdGhpcy52aWV3Q3RvciA9IHRoaXMub3B0aW9ucy52aWV3Q3RvcjtcbiAgICB0aGlzLnZpZXcgPSB0aGlzLmNyZWF0ZVZpZXcoKTtcbiAgfVxuXG4gIC8qKiBAaW5oZXJpdGRvYyAqL1xuICBzdGFydCgpIHtcbiAgICBzdXBlci5zdGFydCgpO1xuXG4gICAgaWYgKCF0aGlzLmhhc1N0YXJ0ZWQpXG4gICAgICB0aGlzLmluaXQoKTtcblxuICAgIGlmIChjbGllbnQuY29tcGF0aWJsZSlcbiAgICAgIHRoaXMucmVhZHkoKTtcbiAgICBlbHNlXG4gICAgICB0aGlzLnNob3coKTtcbiAgfVxuXG4gIC8qKlxuICAgKiBBZGQgYSBuZXcgZmVhdHVyZSBkZWZpbml0aW9uIG9yIG92ZXJyaWRlIGFuIGV4aXN0aW5nIG9uZS5cbiAgICogQHBhcmFtIHtPYmplY3R9IG9iaiAtIFRoZSBkZWZpbml0aW9uIG9mIHRoZSBmZWF0dXJlLlxuICAgKiBAcGFyYW0ge1N0cmluZ30gb2JqLmlkIC0gVGhlIGlkIG9mIHRoZSBkZWZpbml0aW9uLlxuICAgKiBAcGFyYW0ge0Z1bmN0aW9ufSBvYmouY2hlY2sgLSBBIGZ1bmN0aW9uIHJldHVybmluZyB0cnVlIGlmIHRoZSBmZWF0dXJlIGlzXG4gICAqICBhdmFpbGFibGUgb3IgZmFsc2Ugb3RoZXJ3aXNlLlxuICAgKiBAcGFyYW0ge0Z1bmN0aW9ufSBbb2JqLnN0YXJ0SG9vaz11bmRlZmluZWRdIC0gQSBmdW5jdGlvbiB0byBiZSBleGVjdXRlZCBieSB0aGVcbiAgICogIGB3ZWxjb21lYCBzZXJ2aWNlIHdoZW4gc3RhcnRpbmcuXG4gICAqIEBwYXJhbSB7RnVuY3Rpb259IFtvYmouaW50ZXJhY3Rpb25Ib29rPXVuZGVmaW5lZF0gLSBBIGZ1bmN0aW9uIHRvIGJlIGV4ZWN1dGVkIGJ5IHRoZVxuICAgKiAgYHdlbGNvbWVgIHNlcnZpY2Ugd2hlbiB0aGUgdXNlciBpbnRlcmFjdCB3aXRoIHRoZSBkZXZpY2UgKGkuZS4gb24gYGNsaWNrYCBvclxuICAgKiAgYHRvdWNoc3RhcnRgKS5cbiAgICovXG4gIGFkZEZlYXR1cmVEZWZpbml0aW9uKG9iaikge1xuICAgIHRoaXMuX2ZlYXR1cmVEZWZpbml0aW9uc1tvYmouaWRdID0gb2JqO1xuICB9XG5cbiAgLyoqXG4gICAqIEFkZCBmZWF0dXJlKHMpIHRvIHRoZSBvbmVzIHJlcXVpcmVkIGJ5IHRoZSBhcHBsaWNhdGlvbi5cbiAgICogQHBhcmFtIHsuLi5TdHJpbmd9IGZlYXR1cmVzIC0gVGhlIGlkKHMpIG9mIHRoZSBmZWF0dXJlKHMpIHRvIGJlIHJlcXVpcmVkLlxuICAgKi9cbiAgcmVxdWlyZUZlYXR1cmUoLi4uZmVhdHVyZXMpIHtcbiAgICBmZWF0dXJlcy5mb3JFYWNoKChpZCkgPT4gdGhpcy5fcmVxdWlyZWRGZWF0dXJlcy5hZGQoaWQpKTtcbiAgfVxuXG4gIC8qKlxuICAgKiBFeGVjdXRlIGFsbCBgY2hlY2tgIGZ1bmN0aW9ucyBhY2NvcmRpbmcgdG8gdGhlIHJlcXVpcmVkIGZlYXR1cmVzXG4gICAqIEByZXR1cm4ge0Jvb2xlYW59IC0gdHJ1ZSBpZiBhbGwgY2hlY2tzIHBhc3MsIGZhbHNlIG90aGVyd2lzZS5cbiAgICovXG4gIHJlc29sdmVSZXF1aXJlZEZlYXR1cmVzKCkge1xuICAgIGxldCByZXN1bHQgPSB0cnVlO1xuXG4gICAgdGhpcy5fcmVxdWlyZWRGZWF0dXJlcy5mb3JFYWNoKChmZWF0dXJlKSA9PiB7XG4gICAgICBjb25zdCBjaGVja0Z1bmN0aW9uID0gdGhpcy5fZmVhdHVyZURlZmluaXRpb25zW2ZlYXR1cmVdLmNoZWNrO1xuXG4gICAgICBpZiAoISh0eXBlb2YgY2hlY2tGdW5jdGlvbiA9PT0gJ2Z1bmN0aW9uJykpXG4gICAgICAgIHRocm93IG5ldyBFcnJvcihgTm8gY2hlY2sgZnVuY3Rpb24gZGVmaW5lZCBmb3IgJHtmZWF0dXJlfSBmZWF0dXJlYCk7XG5cbiAgICAgIHJlc3VsdCA9IHJlc3VsdCAmJiBjaGVja0Z1bmN0aW9uKCk7XG4gICAgfSk7XG5cbiAgICByZXR1cm4gcmVzdWx0O1xuICB9XG5cbiAgLyoqXG4gICAqIFJldHVybnMgdGhlIGxpc3Qgb2YgdGhlIGZ1bmN0aW9ucyB0byBiZSBleGVjdXRlZCBvbiB3ZWxjb21lIGBzdGFydGAgbGlmZWN5Y2xlLlxuICAgKiBAcmV0dXJuIHtBcnJheX1cbiAgICovXG4gIGdldFN0YXJ0SG9va3MoKSB7XG4gICAgcmV0dXJuIHRoaXMuX2dldEhvb2tzKCdzdGFydEhvb2snKTtcbiAgfVxuXG4gIC8qKlxuICAgKiBSZXR1cm5zIHRoZSBsaXN0IG9mIHRoZSBmdW5jdGlvbnMgdG8gYmUgZXhlY3V0ZWQgb24gd2VsY29tZSB3aGVuIHRoZSB1c2VyXG4gICAqIGludGVyYWN0cyB3aXRoIHRoZSBhcHBsaWNhdGlvbi5cbiAgICogQHJldHVybiB7QXJyYXl9XG4gICAqL1xuICBnZXRJbnRlcmFjdGlvbkhvb2tzKCkge1xuICAgIHJldHVybiB0aGlzLl9nZXRIb29rcygnaW50ZXJhY3Rpb25Ib29rJyk7XG4gIH1cblxuICAvKiogQHByaXZhdGUgKi9cbiAgX2dldEhvb2tzKHR5cGUpIHtcbiAgICBjb25zdCBob29rcyA9IFtdO1xuXG4gICAgdGhpcy5fcmVxdWlyZWRGZWF0dXJlcy5mb3JFYWNoKChmZWF0dXJlKSA9PiB7XG4gICAgICBjb25zdCBob29rID0gdGhpcy5fZmVhdHVyZURlZmluaXRpb25zW2ZlYXR1cmVdW3R5cGVdO1xuXG4gICAgICBpZiAoaG9vaylcbiAgICAgICAgaG9va3MucHVzaChob29rKTtcbiAgICB9KTtcblxuICAgIHJldHVybiBob29rcztcbiAgfVxuXG4gIC8qKlxuICAgKiBQb3B1bGF0ZSBgY2xpZW50LnBsYXRmb3JtYCB3aXRoIHRoZSBwcmVmZXJlZCBhdWRpbyBmaWxlIGV4dGVudGlvblxuICAgKiBmb3IgdGhlIHBsYXRmb3JtLlxuICAgKi9cbiAgX2RlZmluZUF1ZGlvRmlsZUV4dGVudGlvbigpIHtcbiAgICBjb25zdCBhID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnYXVkaW8nKTtcbiAgICAvLyBodHRwOi8vZGl2ZWludG9odG1sNS5pbmZvL2V2ZXJ5dGhpbmcuaHRtbFxuICAgIGlmICghIShhLmNhblBsYXlUeXBlICYmIGEuY2FuUGxheVR5cGUoJ2F1ZGlvL21wZWc7JykpKSB7XG4gICAgICBjbGllbnQucGxhdGZvcm0uYXVkaW9GaWxlRXh0ID0gJy5tcDMnO1xuICAgIH0gZWxzZSBpZiAoISEoYS5jYW5QbGF5VHlwZSAmJiBhLmNhblBsYXlUeXBlKCdhdWRpby9vZ2c7IGNvZGVjcz1cInZvcmJpc1wiJykpKSB7XG4gICAgICBjbGllbnQucGxhdGZvcm0uYXVkaW9GaWxlRXh0ID0gJy5vZ2cnO1xuICAgIH0gZWxzZSB7XG4gICAgICBjbGllbnQucGxhdGZvcm0uYXVkaW9GaWxlRXh0ID0gJy53YXYnO1xuICAgIH1cbiAgfVxuXG4gIC8qKlxuICAgKiBQb3B1bGF0ZSBgY2xpZW50LnBsYXRmb3JtYCB3aXRoIHRoZSBvcyBuYW1lLlxuICAgKi9cbiAgX2RlZmluZVBsYXRmb3JtKCkge1xuICAgIGNvbnN0IHVhID0gd2luZG93Lm5hdmlnYXRvci51c2VyQWdlbnRcbiAgICBjb25zdCBtZCA9IG5ldyBNb2JpbGVEZXRlY3QodWEpO1xuXG4gICAgY2xpZW50LnBsYXRmb3JtLmlzTW9iaWxlID0gKG1kLm1vYmlsZSgpICE9PSBudWxsKTsgLy8gdHJ1ZSBpZiBwaG9uZSBvciB0YWJsZXRcbiAgICBjbGllbnQucGxhdGZvcm0ub3MgPSAoZnVuY3Rpb24oKSB7XG4gICAgICBjb25zdCBvcyA9IG1kLm9zKCk7XG5cbiAgICAgIGlmIChvcyA9PT0gJ0FuZHJvaWRPUycpXG4gICAgICAgIHJldHVybiAnYW5kcm9pZCc7XG4gICAgICBlbHNlIGlmIChvcyA9PT0gJ2lPUycpXG4gICAgICAgIHJldHVybiAnaW9zJztcbiAgICAgIGVsc2VcbiAgICAgICAgcmV0dXJuICdvdGhlcic7XG4gICAgfSkoKTtcbiAgfVxufVxuXG5zZXJ2aWNlTWFuYWdlci5yZWdpc3RlcihTRVJWSUNFX0lELCBQbGF0Zm9ybSk7XG5cbmV4cG9ydCBkZWZhdWx0IFBsYXRmb3JtO1xuIl19