name: gh-pages

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Build Docs
        run: npm run doc

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs

